//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbachieve
{


    
    /// <summary>
    /// 成就等级id
    /// </summary>
    public int id;


    
    /// <summary>
    /// 成就点数
    /// </summary>
    public int score;


    
    /// <summary>
    /// 奖励
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> reward;


    //----------------------Read------------------------
    

    if (id == 成就等级id)
        return playerData.playerData.id;
    

    if (id == 成就点数)
        return playerData.playerData.score;
    

    if (id == 奖励)
        return playerData.playerData.reward;


    //----------------------Write------------------------
    

    if (id == 成就等级id)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 成就点数)
    {
        playerData.playerData.score += value;
    } 

    

    if (id == 奖励)
    {
        playerData.playerData.reward += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.score.ToString());
        

        parasItemsList0[2].SetInputTxt(playerData.playerData.reward.ToString());
}
}