//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbannounce
{


    
    /// <summary>
    /// 公告项id
    /// </summary>
    public int id;


    
    /// <summary>
    /// 公告标题(GM)
    /// </summary>
    public string titleGm;


    
    /// <summary>
    /// 公告链接
    /// </summary>
    public string link;


    
    /// <summary>
    /// 正文备注
    /// </summary>
    public string remarkGm;


    
    /// <summary>
    /// 有效期(天数)
    /// </summary>
    public int valid;


    //----------------------Read------------------------
    

    if (id == 公告项id)
        return playerData.playerData.id;
    

    if (id == 公告标题(GM))
        return playerData.playerData.titleGm;
    

    if (id == 公告链接)
        return playerData.playerData.link;
    

    if (id == 正文备注)
        return playerData.playerData.remarkGm;
    

    if (id == 有效期(天数))
        return playerData.playerData.valid;


    //----------------------Write------------------------
    

    if (id == 公告项id)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 公告标题(GM))
    {
        playerData.playerData.titleGm += value;
    } 

    

    if (id == 公告链接)
    {
        playerData.playerData.link += value;
    } 

    

    if (id == 正文备注)
    {
        playerData.playerData.remarkGm += value;
    } 

    

    if (id == 有效期(天数))
    {
        playerData.playerData.valid += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.titleGm.ToString());
        

        parasItemsList0[2].SetInputTxt(playerData.playerData.link.ToString());
        

        parasItemsList0[3].SetInputTxt(playerData.playerData.remarkGm.ToString());
        

        parasItemsList0[4].SetInputTxt(playerData.playerData.valid.ToString());
}
}