//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbbattlepass_exp
{


    
    /// <summary>
    /// 等级
    /// </summary>
    public int id;


    
    /// <summary>
    /// 总经验
    /// </summary>
    public int exp;


    //----------------------Read------------------------
    

    if (id == 等级)
        return playerData.playerData.id;
    

    if (id == 总经验)
        return playerData.playerData.exp;


    //----------------------Write------------------------
    

    if (id == 等级)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 总经验)
    {
        playerData.playerData.exp += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.exp.ToString());
}
}