//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbbattle_item
{


    
    /// <summary>
    /// id
    /// </summary>
    public int id;


    
    /// <summary>
    /// 道具类型
    /// </summary>
    public int type;


    
    /// <summary>
    /// 效果类型
    /// </summary>
    public int effectType;


    
    /// <summary>
    /// 道具效果
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> effect;


    
    /// <summary>
    /// 每局获取上限
    /// </summary>
    public int maxNum;


    //----------------------Read------------------------
    

    if (id == id)
        return playerData.playerData.id;
    

    if (id == 道具类型)
        return playerData.playerData.type;
    

    if (id == 效果类型)
        return playerData.playerData.effectType;
    

    if (id == 道具效果)
        return playerData.playerData.effect;
    

    if (id == 每局获取上限)
        return playerData.playerData.maxNum;


    //----------------------Write------------------------
    

    if (id == id)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 道具类型)
    {
        playerData.playerData.type += value;
    } 

    

    if (id == 效果类型)
    {
        playerData.playerData.effectType += value;
    } 

    

    if (id == 道具效果)
    {
        playerData.playerData.effect += value;
    } 

    

    if (id == 每局获取上限)
    {
        playerData.playerData.maxNum += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.type.ToString());
        

        parasItemsList0[2].SetInputTxt(playerData.playerData.effectType.ToString());
        

        parasItemsList0[3].SetInputTxt(playerData.playerData.effect.ToString());
        

        parasItemsList0[4].SetInputTxt(playerData.playerData.maxNum.ToString());
}
}