//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbbattle_status
{


    
    /// <summary>
    /// 状态id
    /// </summary>
    public int id;


    //----------------------Read------------------------
    

    if (id == 状态id)
        return playerData.playerData.id;


    //----------------------Write------------------------
    

    if (id == 状态id)
    {
        playerData.playerData.id += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
}
}