//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbdays_sign
{


    
    /// <summary>
    /// ID
    /// </summary>
    public int id;


    
    /// <summary>
    /// 备注
    /// </summary>
    public string nameGm;


    
    /// <summary>
    /// 模块id
    /// </summary>
    public int tagFunc;


    
    /// <summary>
    /// 有效期
    /// </summary>
    public int valid;


    //----------------------Read------------------------
    

    if (id == ID)
        return playerData.playerData.id;
    

    if (id == 备注)
        return playerData.playerData.nameGm;
    

    if (id == 模块id)
        return playerData.playerData.tagFunc;
    

    if (id == 有效期)
        return playerData.playerData.valid;


    //----------------------Write------------------------
    

    if (id == ID)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 备注)
    {
        playerData.playerData.nameGm += value;
    } 

    

    if (id == 模块id)
    {
        playerData.playerData.tagFunc += value;
    } 

    

    if (id == 有效期)
    {
        playerData.playerData.valid += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.nameGm.ToString());
        

        parasItemsList0[2].SetInputTxt(playerData.playerData.tagFunc.ToString());
        

        parasItemsList0[3].SetInputTxt(playerData.playerData.valid.ToString());
}
}