//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbequip_level
{


    
    /// <summary>
    /// 等级Id
    /// </summary>
    public int id;


    
    /// <summary>
    /// 武器消耗
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> cost1;


    
    /// <summary>
    /// 衣服消耗
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> cost2;


    
    /// <summary>
    /// 手套消耗
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> cost3;


    
    /// <summary>
    /// 裤子消耗
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> cost4;


    
    /// <summary>
    /// 腰带消耗
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> cost5;


    
    /// <summary>
    /// 鞋子消耗
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> cost6;


    //----------------------Read------------------------
    

    if (id == 等级Id)
        return playerData.playerData.id;
    

    if (id == 武器消耗)
        return playerData.playerData.cost1;
    

    if (id == 衣服消耗)
        return playerData.playerData.cost2;
    

    if (id == 手套消耗)
        return playerData.playerData.cost3;
    

    if (id == 裤子消耗)
        return playerData.playerData.cost4;
    

    if (id == 腰带消耗)
        return playerData.playerData.cost5;
    

    if (id == 鞋子消耗)
        return playerData.playerData.cost6;


    //----------------------Write------------------------
    

    if (id == 等级Id)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 武器消耗)
    {
        playerData.playerData.cost1 += value;
    } 

    

    if (id == 衣服消耗)
    {
        playerData.playerData.cost2 += value;
    } 

    

    if (id == 手套消耗)
    {
        playerData.playerData.cost3 += value;
    } 

    

    if (id == 裤子消耗)
    {
        playerData.playerData.cost4 += value;
    } 

    

    if (id == 腰带消耗)
    {
        playerData.playerData.cost5 += value;
    } 

    

    if (id == 鞋子消耗)
    {
        playerData.playerData.cost6 += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.cost1.ToString());
        

        parasItemsList0[2].SetInputTxt(playerData.playerData.cost2.ToString());
        

        parasItemsList0[3].SetInputTxt(playerData.playerData.cost3.ToString());
        

        parasItemsList0[4].SetInputTxt(playerData.playerData.cost4.ToString());
        

        parasItemsList0[5].SetInputTxt(playerData.playerData.cost5.ToString());
        

        parasItemsList0[6].SetInputTxt(playerData.playerData.cost6.ToString());
}
}