//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbequip_pos
{


    
    /// <summary>
    /// 部位id
    /// </summary>
    public int id;


    
    /// <summary>
    /// 描述
    /// </summary>
    public string desc;


    
    /// <summary>
    /// 图片
    /// </summary>
    public string pic;


    
    /// <summary>
    /// 空图片
    /// </summary>
    public string blank;


    //----------------------Read------------------------
    

    if (id == 部位id)
        return playerData.playerData.id;
    

    if (id == 描述)
        return playerData.playerData.desc;
    

    if (id == 图片)
        return playerData.playerData.pic;
    

    if (id == 空图片)
        return playerData.playerData.blank;


    //----------------------Write------------------------
    

    if (id == 部位id)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 描述)
    {
        playerData.playerData.desc += value;
    } 

    

    if (id == 图片)
    {
        playerData.playerData.pic += value;
    } 

    

    if (id == 空图片)
    {
        playerData.playerData.blank += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.desc.ToString());
        

        parasItemsList0[2].SetInputTxt(playerData.playerData.pic.ToString());
        

        parasItemsList0[3].SetInputTxt(playerData.playerData.blank.ToString());
}
}