//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbfund
{


    
    /// <summary>
    /// ID
    /// </summary>
    public int id;


    
    /// <summary>
    /// 解锁等级
    /// </summary>
    public int unlockLevel;


    
    /// <summary>
    /// 付费线1价格
    /// </summary>
    public int price1;


    
    /// <summary>
    /// 付费线2价格
    /// </summary>
    public int price2;


    //----------------------Read------------------------
    

    if (id == ID)
        return playerData.playerData.id;
    

    if (id == 解锁等级)
        return playerData.playerData.unlockLevel;
    

    if (id == 付费线1价格)
        return playerData.playerData.price1;
    

    if (id == 付费线2价格)
        return playerData.playerData.price2;


    //----------------------Write------------------------
    

    if (id == ID)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 解锁等级)
    {
        playerData.playerData.unlockLevel += value;
    } 

    

    if (id == 付费线1价格)
    {
        playerData.playerData.price1 += value;
    } 

    

    if (id == 付费线2价格)
    {
        playerData.playerData.price2 += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.unlockLevel.ToString());
        

        parasItemsList0[2].SetInputTxt(playerData.playerData.price1.ToString());
        

        parasItemsList0[3].SetInputTxt(playerData.playerData.price2.ToString());
}
}