//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbgoods
{


    
    /// <summary>
    /// id
    /// </summary>
    public int id;


    
    /// <summary>
    /// 商品编码
    /// </summary>
    public string num;


    
    /// <summary>
    /// 商品表
    /// </summary>
    public string table;


    
    /// <summary>
    /// ID字段
    /// </summary>
    public string idField;


    
    /// <summary>
    /// 价格字段
    /// </summary>
    public string priceField;


    //----------------------Read------------------------
    

    if (id == id)
        return playerData.playerData.id;
    

    if (id == 商品编码)
        return playerData.playerData.num;
    

    if (id == 商品表)
        return playerData.playerData.table;
    

    if (id == ID字段)
        return playerData.playerData.idField;
    

    if (id == 价格字段)
        return playerData.playerData.priceField;


    //----------------------Write------------------------
    

    if (id == id)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 商品编码)
    {
        playerData.playerData.num += value;
    } 

    

    if (id == 商品表)
    {
        playerData.playerData.table += value;
    } 

    

    if (id == ID字段)
    {
        playerData.playerData.idField += value;
    } 

    

    if (id == 价格字段)
    {
        playerData.playerData.priceField += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.num.ToString());
        

        parasItemsList0[2].SetInputTxt(playerData.playerData.table.ToString());
        

        parasItemsList0[3].SetInputTxt(playerData.playerData.idField.ToString());
        

        parasItemsList0[4].SetInputTxt(playerData.playerData.priceField.ToString());
}
}