//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbmail
{


    
    /// <summary>
    /// 邮件id
    /// </summary>
    public int id;


    
    /// <summary>
    /// 邮件类型
    /// </summary>
    public int type;


    
    /// <summary>
    /// 邮件标题(GM)
    /// </summary>
    public string titleGm;


    
    /// <summary>
    /// 邮件正文(GM)
    /// </summary>
    public string contentGm;


    
    /// <summary>
    /// 文本参数
    /// </summary>
    public System.Collections.Generic.List<string> para;


    
    /// <summary>
    /// 有效期(天数)
    /// </summary>
    public int valid;


    
    /// <summary>
    /// 奖励
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> reward;


    //----------------------Read------------------------
    

    if (id == 邮件id)
        return playerData.playerData.id;
    

    if (id == 邮件类型)
        return playerData.playerData.type;
    

    if (id == 邮件标题(GM))
        return playerData.playerData.titleGm;
    

    if (id == 邮件正文(GM))
        return playerData.playerData.contentGm;
    

    if (id == 文本参数)
        return playerData.playerData.para;
    

    if (id == 有效期(天数))
        return playerData.playerData.valid;
    

    if (id == 奖励)
        return playerData.playerData.reward;


    //----------------------Write------------------------
    

    if (id == 邮件id)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 邮件类型)
    {
        playerData.playerData.type += value;
    } 

    

    if (id == 邮件标题(GM))
    {
        playerData.playerData.titleGm += value;
    } 

    

    if (id == 邮件正文(GM))
    {
        playerData.playerData.contentGm += value;
    } 

    

    if (id == 文本参数)
    {
        playerData.playerData.para += value;
    } 

    

    if (id == 有效期(天数))
    {
        playerData.playerData.valid += value;
    } 

    

    if (id == 奖励)
    {
        playerData.playerData.reward += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.type.ToString());
        

        parasItemsList0[2].SetInputTxt(playerData.playerData.titleGm.ToString());
        

        parasItemsList0[3].SetInputTxt(playerData.playerData.contentGm.ToString());
        

        parasItemsList0[4].SetInputTxt(playerData.playerData.para.ToString());
        

        parasItemsList0[5].SetInputTxt(playerData.playerData.valid.ToString());
        

        parasItemsList0[6].SetInputTxt(playerData.playerData.reward.ToString());
}
}