//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbmonopoly_event_lotto
{


    
    /// <summary>
    /// id
    /// </summary>
    public int id;


    
    /// <summary>
    /// 分组
    /// </summary>
    public int group;


    
    /// <summary>
    /// 基础值
    /// </summary>
    public int base0;


    
    /// <summary>
    /// 倍率
    /// </summary>
    public int multiplier;


    
    /// <summary>
    /// 权重
    /// </summary>
    public int power;


    //----------------------Read------------------------
    

    if (id == id)
        return playerData.playerData.id;
    

    if (id == 分组)
        return playerData.playerData.group;
    

    if (id == 基础值)
        return playerData.playerData.base0;
    

    if (id == 倍率)
        return playerData.playerData.multiplier;
    

    if (id == 权重)
        return playerData.playerData.power;


    //----------------------Write------------------------
    

    if (id == id)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 分组)
    {
        playerData.playerData.group += value;
    } 

    

    if (id == 基础值)
    {
        playerData.playerData.base0 += value;
    } 

    

    if (id == 倍率)
    {
        playerData.playerData.multiplier += value;
    } 

    

    if (id == 权重)
    {
        playerData.playerData.power += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.group.ToString());
        

        parasItemsList0[2].SetInputTxt(playerData.playerData.base0.ToString());
        

        parasItemsList0[3].SetInputTxt(playerData.playerData.multiplier.ToString());
        

        parasItemsList0[4].SetInputTxt(playerData.playerData.power.ToString());
}
}