//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbmonthly
{


    
    /// <summary>
    /// ID
    /// </summary>
    public int id;


    
    /// <summary>
    /// 特殊收益
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector2> userVariable;


    
    /// <summary>
    /// 价格
    /// </summary>
    public int price;


    
    /// <summary>
    /// 奖励
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> reward;


    
    /// <summary>
    /// 每日奖励
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> rewardDaily;


    //----------------------Read------------------------
    

    if (id == ID)
        return playerData.playerData.id;
    

    if (id == 特殊收益)
        return playerData.playerData.userVariable;
    

    if (id == 价格)
        return playerData.playerData.price;
    

    if (id == 奖励)
        return playerData.playerData.reward;
    

    if (id == 每日奖励)
        return playerData.playerData.rewardDaily;


    //----------------------Write------------------------
    

    if (id == ID)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 特殊收益)
    {
        playerData.playerData.userVariable += value;
    } 

    

    if (id == 价格)
    {
        playerData.playerData.price += value;
    } 

    

    if (id == 奖励)
    {
        playerData.playerData.reward += value;
    } 

    

    if (id == 每日奖励)
    {
        playerData.playerData.rewardDaily += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.userVariable.ToString());
        

        parasItemsList0[2].SetInputTxt(playerData.playerData.price.ToString());
        

        parasItemsList0[3].SetInputTxt(playerData.playerData.reward.ToString());
        

        parasItemsList0[4].SetInputTxt(playerData.playerData.rewardDaily.ToString());
}
}