//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbsetting
{


    
    /// <summary>
    /// 默认值
    /// </summary>
    public int init;


    //----------------------Read------------------------
    

    if (id == 默认值)
        return playerData.playerData.init;


    //----------------------Write------------------------
    

    if (id == 默认值)
    {
        playerData.playerData.init += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.init.ToString());
}
}