//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbskill
{


    
    /// <summary>
    /// 技能id
    /// </summary>
    public int id;


    
    /// <summary>
    /// 技能效果组
    /// </summary>
    public System.Collections.Generic.List<int> skillEffectArray;


    
    /// <summary>
    /// 全局事件
    /// </summary>
    public System.Collections.Generic.List<int> skillEventArray;


    
    /// <summary>
    /// 替换技能
    /// </summary>
    public int replaceSkillId;


    //----------------------Read------------------------
    

    if (id == 技能id)
        return playerData.playerData.id;
    

    if (id == 技能效果组)
        return playerData.playerData.skillEffectArray;
    

    if (id == 全局事件)
        return playerData.playerData.skillEventArray;
    

    if (id == 替换技能)
        return playerData.playerData.replaceSkillId;


    //----------------------Write------------------------
    

    if (id == 技能id)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 技能效果组)
    {
        playerData.playerData.skillEffectArray += value;
    } 

    

    if (id == 全局事件)
    {
        playerData.playerData.skillEventArray += value;
    } 

    

    if (id == 替换技能)
    {
        playerData.playerData.replaceSkillId += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.skillEffectArray.ToString());
        

        parasItemsList0[2].SetInputTxt(playerData.playerData.skillEventArray.ToString());
        

        parasItemsList0[3].SetInputTxt(playerData.playerData.replaceSkillId.ToString());
}
}