//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbsweep_times
{


    
    /// <summary>
    /// 整顿倍数id
    /// </summary>
    public int id;


    
    /// <summary>
    /// 倍率
    /// </summary>
    public int times;


    //----------------------Read------------------------
    

    if (id == 整顿倍数id)
        return playerData.playerData.id;
    

    if (id == 倍率)
        return playerData.playerData.times;


    //----------------------Write------------------------
    

    if (id == 整顿倍数id)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 倍率)
    {
        playerData.playerData.times += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.times.ToString());
}
}