//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbtalent
{


    
    /// <summary>
    /// 天赋Id
    /// </summary>
    public int id;


    
    /// <summary>
    /// 类型
    /// </summary>
    public int type;


    
    /// <summary>
    /// 前置天赋
    /// </summary>
    public int preId;


    
    /// <summary>
    /// 属性天赋
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector2> attr;


    
    /// <summary>
    /// 技能天赋
    /// </summary>
    public int skill;


    
    /// <summary>
    /// 等级
    /// </summary>
    public int level;


    
    /// <summary>
    /// 消耗
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> cost;


    //----------------------Read------------------------
    

    if (id == 天赋Id)
        return playerData.playerData.id;
    

    if (id == 类型)
        return playerData.playerData.type;
    

    if (id == 前置天赋)
        return playerData.playerData.preId;
    

    if (id == 属性天赋)
        return playerData.playerData.attr;
    

    if (id == 技能天赋)
        return playerData.playerData.skill;
    

    if (id == 等级)
        return playerData.playerData.level;
    

    if (id == 消耗)
        return playerData.playerData.cost;


    //----------------------Write------------------------
    

    if (id == 天赋Id)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 类型)
    {
        playerData.playerData.type += value;
    } 

    

    if (id == 前置天赋)
    {
        playerData.playerData.preId += value;
    } 

    

    if (id == 属性天赋)
    {
        playerData.playerData.attr += value;
    } 

    

    if (id == 技能天赋)
    {
        playerData.playerData.skill += value;
    } 

    

    if (id == 等级)
    {
        playerData.playerData.level += value;
    } 

    

    if (id == 消耗)
    {
        playerData.playerData.cost += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.type.ToString());
        

        parasItemsList0[2].SetInputTxt(playerData.playerData.preId.ToString());
        

        parasItemsList0[3].SetInputTxt(playerData.playerData.attr.ToString());
        

        parasItemsList0[4].SetInputTxt(playerData.playerData.skill.ToString());
        

        parasItemsList0[5].SetInputTxt(playerData.playerData.level.ToString());
        

        parasItemsList0[6].SetInputTxt(playerData.playerData.cost.ToString());
}
}