//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbtask_group
{


    
    /// <summary>
    /// 任务组id
    /// </summary>
    public int id;


    
    /// <summary>
    /// 所属模块id
    /// </summary>
    public int tagFunc;


    
    /// <summary>
    /// 天数
    /// </summary>
    public int day;


    //----------------------Read------------------------
    

    if (id == 任务组id)
        return playerData.playerData.id;
    

    if (id == 所属模块id)
        return playerData.playerData.tagFunc;
    

    if (id == 天数)
        return playerData.playerData.day;


    //----------------------Write------------------------
    

    if (id == 任务组id)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 所属模块id)
    {
        playerData.playerData.tagFunc += value;
    } 

    

    if (id == 天数)
    {
        playerData.playerData.day += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.tagFunc.ToString());
        

        parasItemsList0[2].SetInputTxt(playerData.playerData.day.ToString());
}
}