//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbtask
{


    
    /// <summary>
    /// 任务id
    /// </summary>
    public int id;


    
    /// <summary>
    /// 所属组
    /// </summary>
    public int group;


    
    /// <summary>
    /// 任务接取条件
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> condition;


    
    /// <summary>
    /// 任务奖励
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> reward;


    
    /// <summary>
    /// 任务类型
    /// </summary>
    public int type;


    
    /// <summary>
    /// 任务参数
    /// </summary>
    public System.Collections.Generic.List<int> para;


    
    /// <summary>
    /// 点数
    /// </summary>
    public int score;


    //----------------------Read------------------------
    

    if (id == 任务id)
        return playerData.playerData.id;
    

    if (id == 所属组)
        return playerData.playerData.group;
    

    if (id == 任务接取条件)
        return playerData.playerData.condition;
    

    if (id == 任务奖励)
        return playerData.playerData.reward;
    

    if (id == 任务类型)
        return playerData.playerData.type;
    

    if (id == 任务参数)
        return playerData.playerData.para;
    

    if (id == 点数)
        return playerData.playerData.score;


    //----------------------Write------------------------
    

    if (id == 任务id)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 所属组)
    {
        playerData.playerData.group += value;
    } 

    

    if (id == 任务接取条件)
    {
        playerData.playerData.condition += value;
    } 

    

    if (id == 任务奖励)
    {
        playerData.playerData.reward += value;
    } 

    

    if (id == 任务类型)
    {
        playerData.playerData.type += value;
    } 

    

    if (id == 任务参数)
    {
        playerData.playerData.para += value;
    } 

    

    if (id == 点数)
    {
        playerData.playerData.score += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.group.ToString());
        

        parasItemsList0[2].SetInputTxt(playerData.playerData.condition.ToString());
        

        parasItemsList0[3].SetInputTxt(playerData.playerData.reward.ToString());
        

        parasItemsList0[4].SetInputTxt(playerData.playerData.type.ToString());
        

        parasItemsList0[5].SetInputTxt(playerData.playerData.para.ToString());
        

        parasItemsList0[6].SetInputTxt(playerData.playerData.score.ToString());
}
}