//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbuser_avatar
{


    
    /// <summary>
    /// id
    /// </summary>
    public int id;


    
    /// <summary>
    /// 类型
    /// </summary>
    public int type;


    
    /// <summary>
    /// 品质
    /// </summary>
    public int quality;


    //----------------------Read------------------------
    

    if (id == id)
        return playerData.playerData.id;
    

    if (id == 类型)
        return playerData.playerData.type;
    

    if (id == 品质)
        return playerData.playerData.quality;


    //----------------------Write------------------------
    

    if (id == id)
    {
        playerData.playerData.id += value;
    } 

    

    if (id == 类型)
    {
        playerData.playerData.type += value;
    } 

    

    if (id == 品质)
    {
        playerData.playerData.quality += value;
    } 

        //----------------------参数面板------------------------
          
        

        parasItemsList0[0].SetInputTxt(playerData.playerData.id.ToString());
        

        parasItemsList0[1].SetInputTxt(playerData.playerData.type.ToString());
        

        parasItemsList0[2].SetInputTxt(playerData.playerData.quality.ToString());
}
}