// <auto-generated />
using JuiceZombies.Server.Datas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JuiceZombies.Server.Migrations
{
    [DbContext(typeof(MyPostgresDbContext))]
    [Migration("20250827145235_AddGoldsToUserResDatasTable")]
    partial class AddGoldsToUserResDatasTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JuiceZombies.Server.Datas.ShopData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GameUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("buyedMonthCardms")
                        .HasColumnType("integer");

                    b.Property<bool>("isBuyADCard")
                        .HasColumnType("boolean");

                    b.Property<bool>("isBuyMonthCard")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GameUserId")
                        .IsUnique();

                    b.ToTable("ShopDatas");
                });

            modelBuilder.Entity("JuiceZombies.Server.Datas.UserResData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Diamonds")
                        .HasColumnType("bigint");

                    b.Property<long>("Golds")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("UserResDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
