//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class tag_func :  Bright.Config.BeanBase 
{
    public tag_func(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        PostInit();
    }

    public tag_func(int id ) 
    {
        this.id = id;
        PostInit();
    }

    public static tag_func Deserializetag_func(JSONNode _json)
    {
        return new config.tag_func(_json);
    }

    /// <summary>
    /// 模块id
    /// </summary>
    public int id { get; private set; }

    public const int __ID__ = 238142837;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
