//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class task_group :  Bright.Config.BeanBase 
{
    public task_group(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        { if(!_json["tag_func"].IsNumber) { throw new SerializationException(); }  tagFunc = _json["tag_func"]; }
        { if(!_json["day"].IsNumber) { throw new SerializationException(); }  day = _json["day"]; }
        { if(!_json["type"].IsNumber) { throw new SerializationException(); }  type = _json["type"]; }
        PostInit();
    }

    public task_group(int id, int tag_func, int day, int type ) 
    {
        this.id = id;
        this.tagFunc = tag_func;
        this.day = day;
        this.type = type;
        PostInit();
    }

    public static task_group Deserializetask_group(JSONNode _json)
    {
        return new config.task_group(_json);
    }

    /// <summary>
    /// 任务组id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 所属模块id
    /// </summary>
    public int tagFunc { get; private set; }
    /// <summary>
    /// 天数
    /// </summary>
    public int day { get; private set; }
    /// <summary>
    /// 任务类型
    /// </summary>
    public int type { get; private set; }

    public const int __ID__ = -1787169423;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "tagFunc:" + tagFunc + ","
        + "day:" + day + ","
        + "type:" + type + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
