//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class achieve_group :  Bright.Config.BeanBase 
{
    public achieve_group(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        { var __json0 = _json["group_id"]; if(!__json0.IsArray) { throw new SerializationException(); } groupId = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  groupId.Add(__v0); }   }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  name = _json["name"]; }
        { if(!_json["icon"].IsString) { throw new SerializationException(); }  icon = _json["icon"]; }
        PostInit();
    }

    public achieve_group(int id, System.Collections.Generic.List<int> group_id, string name, string icon ) 
    {
        this.id = id;
        this.groupId = group_id;
        this.name = name;
        this.icon = icon;
        
        PostInit();
    }

    public static achieve_group Deserializeachieve_group(JSONNode _json)
    {
        return new config.achieve_group(_json);
    }

    /// <summary>
    /// 成就组id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 任务组id
    /// </summary>
    public System.Collections.Generic.List<int> groupId { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string name { get; private set; }
    /// <summary>
    /// 图标(图片资源)
    /// </summary>
    public string icon { get; private set; }
    public const int __ID__ = -1933081243;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "groupId:" + Bright.Common.StringUtil.CollectionToString(groupId) + ","
        + "name:" + name + ","
        + "icon:" + icon + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}