//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class battleshop_drop :  Bright.Config.BeanBase 
{
    public battleshop_drop(JSONNode _json) 
    {
        { if(!_json["assist"].IsNumber) { throw new SerializationException(); }  assist = _json["assist"]; }
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        { if(!_json["quality"].IsNumber) { throw new SerializationException(); }  quality = _json["quality"]; }
        { if(!_json["power"].IsNumber) { throw new SerializationException(); }  power = _json["power"]; }
        PostInit();
    }

    public battleshop_drop(int assist, int id, int quality, int power ) 
    {
        this.assist = assist;
        this.id = id;
        this.quality = quality;
        this.power = power;
        
        PostInit();
    }

    public static battleshop_drop Deserializebattleshop_drop(JSONNode _json)
    {
        return new config.battleshop_drop(_json);
    }

    /// <summary>
    /// 辅助主键id
    /// </summary>
    public int assist { get; private set; }
    /// <summary>
    /// 刷新池id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 技能品质id
    /// </summary>
    public int quality { get; private set; }
    /// <summary>
    /// 权重
    /// </summary>
    public int power { get; private set; }
    public const int __ID__ = -792063436;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "assist:" + assist + ","
        + "id:" + id + ","
        + "quality:" + quality + ","
        + "power:" + power + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}