//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class battlepass_reward :  Bright.Config.BeanBase 
{
    public battlepass_reward(JSONNode _json) 
    {
        { if(!_json["assist"].IsNumber) { throw new SerializationException(); }  assist = _json["assist"]; }
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        { if(!_json["level"].IsNumber) { throw new SerializationException(); }  level = _json["level"]; }
        { var __json0 = _json["reward1"]; if(!__json0.IsArray) { throw new SerializationException(); } reward1 = new System.Collections.Generic.List<UnityEngine.Vector3>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { UnityEngine.Vector3 __v0;  { var _json2 = __e0; if(!_json2.IsObject) { throw new SerializationException(); } float __x; { if(!_json2["x"].IsNumber) { throw new SerializationException(); }  __x = _json2["x"]; } float __y; { if(!_json2["y"].IsNumber) { throw new SerializationException(); }  __y = _json2["y"]; } float __z; { if(!_json2["z"].IsNumber) { throw new SerializationException(); }  __z = _json2["z"]; }  __v0 = new UnityEngine.Vector3(__x, __y,__z); }  reward1.Add(__v0); }   }
        { var __json0 = _json["reward2"]; if(!__json0.IsArray) { throw new SerializationException(); } reward2 = new System.Collections.Generic.List<UnityEngine.Vector3>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { UnityEngine.Vector3 __v0;  { var _json2 = __e0; if(!_json2.IsObject) { throw new SerializationException(); } float __x; { if(!_json2["x"].IsNumber) { throw new SerializationException(); }  __x = _json2["x"]; } float __y; { if(!_json2["y"].IsNumber) { throw new SerializationException(); }  __y = _json2["y"]; } float __z; { if(!_json2["z"].IsNumber) { throw new SerializationException(); }  __z = _json2["z"]; }  __v0 = new UnityEngine.Vector3(__x, __y,__z); }  reward2.Add(__v0); }   }
        PostInit();
    }

    public battlepass_reward(int assist, int id, int level, System.Collections.Generic.List<UnityEngine.Vector3> reward1, System.Collections.Generic.List<UnityEngine.Vector3> reward2 ) 
    {
        this.assist = assist;
        this.id = id;
        this.level = level;
        this.reward1 = reward1;
        this.reward2 = reward2;
        
        PostInit();
    }

    public static battlepass_reward Deserializebattlepass_reward(JSONNode _json)
    {
        return new config.battlepass_reward(_json);
    }

    /// <summary>
    /// 辅助主键id
    /// </summary>
    public int assist { get; private set; }
    /// <summary>
    /// 通行证ID
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 通行证等级
    /// </summary>
    public int level { get; private set; }
    /// <summary>
    /// 免费线
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> reward1 { get; private set; }
    /// <summary>
    /// 付费线
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> reward2 { get; private set; }
    public const int __ID__ = -104626247;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "assist:" + assist + ","
        + "id:" + id + ","
        + "level:" + level + ","
        + "reward1:" + Bright.Common.StringUtil.CollectionToString(reward1) + ","
        + "reward2:" + Bright.Common.StringUtil.CollectionToString(reward2) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}