//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class battleshop_stage :  Bright.Config.BeanBase 
{
    public battleshop_stage(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        { if(!_json["stage"].IsNumber) { throw new SerializationException(); }  stage = _json["stage"]; }
        { if(!_json["stage_detail"].IsNumber) { throw new SerializationException(); }  stageDetail = _json["stage_detail"]; }
        { if(!_json["battleshop_drop_id"].IsNumber) { throw new SerializationException(); }  battleshopDropId = _json["battleshop_drop_id"]; }
        PostInit();
    }

    public battleshop_stage(int id, int stage, int stage_detail, int battleshop_drop_id ) 
    {
        this.id = id;
        this.stage = stage;
        this.stageDetail = stage_detail;
        this.battleshopDropId = battleshop_drop_id;
        
        PostInit();
    }

    public static battleshop_stage Deserializebattleshop_stage(JSONNode _json)
    {
        return new config.battleshop_stage(_json);
    }

    /// <summary>
    /// 商店阶段id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 阶段数
    /// </summary>
    public int stage { get; private set; }
    /// <summary>
    /// 子阶段数
    /// </summary>
    public int stageDetail { get; private set; }
    /// <summary>
    /// 刷新池id
    /// </summary>
    public int battleshopDropId { get; private set; }
    public const int __ID__ = 1229736025;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "stage:" + stage + ","
        + "stageDetail:" + stageDetail + ","
        + "battleshopDropId:" + battleshopDropId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}