//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class draw_banner :  Bright.Config.BeanBase 
{
    public draw_banner(JSONNode _json) 
    {
        { if(!_json["assist"].IsNumber) { throw new SerializationException(); }  assist = _json["assist"]; }
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        { if(!_json["quality"].IsNumber) { throw new SerializationException(); }  quality = _json["quality"]; }
        { var __json0 = _json["info"]; if(!__json0.IsArray) { throw new SerializationException(); } info = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  info.Add(__v0); }   }
        { if(!_json["power"].IsNumber) { throw new SerializationException(); }  power = _json["power"]; }
        PostInit();
    }

    public draw_banner(int assist, int id, int quality, System.Collections.Generic.List<int> info, int power ) 
    {
        this.assist = assist;
        this.id = id;
        this.quality = quality;
        this.info = info;
        this.power = power;
        
        PostInit();
    }

    public static draw_banner Deserializedraw_banner(JSONNode _json)
    {
        return new config.draw_banner(_json);
    }

    /// <summary>
    /// 辅助主键id
    /// </summary>
    public int assist { get; private set; }
    /// <summary>
    /// bannerID
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 品质
    /// </summary>
    public int quality { get; private set; }
    /// <summary>
    /// 装备id
    /// </summary>
    public System.Collections.Generic.List<int> info { get; private set; }
    /// <summary>
    /// 权重
    /// </summary>
    public int power { get; private set; }
    public const int __ID__ = 1822425563;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "assist:" + assist + ","
        + "id:" + id + ","
        + "quality:" + quality + ","
        + "info:" + Bright.Common.StringUtil.CollectionToString(info) + ","
        + "power:" + power + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}