//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class element :  Bright.Config.BeanBase 
{
    public element(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        { if(!_json["time"].IsNumber) { throw new SerializationException(); }  time = _json["time"]; }
        PostInit();
    }

    public element(int id, int time ) 
    {
        this.id = id;
        this.time = time;
        
        PostInit();
    }

    public static element Deserializeelement(JSONNode _json)
    {
        return new config.element(_json);
    }

    /// <summary>
    /// 元素id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 状态持续时间
    /// </summary>
    public int time { get; private set; }
    public const int __ID__ = -2046144432;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "time:" + time + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}