//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class monopoly_event :  Bright.Config.BeanBase 
{
    public monopoly_event(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        { if(!_json["pic"].IsString) { throw new SerializationException(); }  pic = _json["pic"]; }
        PostInit();
    }

    public monopoly_event(int id, string pic ) 
    {
        this.id = id;
        this.pic = pic;
        
        PostInit();
    }

    public static monopoly_event Deserializemonopoly_event(JSONNode _json)
    {
        return new config.monopoly_event(_json);
    }

    /// <summary>
    /// 事件id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 图片(图片资源)
    /// </summary>
    public string pic { get; private set; }
    public const int __ID__ = 363923382;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "pic:" + pic + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}