//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class monster_attr :  Bright.Config.BeanBase 
{
    public monster_attr(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        { if(!_json["type"].IsNumber) { throw new SerializationException(); }  type = _json["type"]; }
        { if(!_json["book_id"].IsNumber) { throw new SerializationException(); }  bookId = _json["book_id"]; }
        { if(!_json["model_size"].IsNumber) { throw new SerializationException(); }  modelSize = _json["model_size"]; }
        { if(!_json["force"].IsNumber) { throw new SerializationException(); }  force = _json["force"]; }
        { if(!_json["speed"].IsNumber) { throw new SerializationException(); }  speed = _json["speed"]; }
        { if(!_json["change_dir_yn"].IsNumber) { throw new SerializationException(); }  changeDirYn = _json["change_dir_yn"]; }
        { if(!_json["mass"].IsNumber) { throw new SerializationException(); }  mass = _json["mass"]; }
        { if(!_json["repel_resist_addition"].IsNumber) { throw new SerializationException(); }  repelResistAddition = _json["repel_resist_addition"]; }
        { if(!_json["atk"].IsNumber) { throw new SerializationException(); }  atk = _json["atk"]; }
        { if(!_json["hp"].IsNumber) { throw new SerializationException(); }  hp = _json["hp"]; }
        PostInit();
    }

    public monster_attr(int id, int type, int book_id, int model_size, int force, int speed, int change_dir_yn, int mass, int repel_resist_addition, int atk, int hp ) 
    {
        this.id = id;
        this.type = type;
        this.bookId = book_id;
        this.modelSize = model_size;
        this.force = force;
        this.speed = speed;
        this.changeDirYn = change_dir_yn;
        this.mass = mass;
        this.repelResistAddition = repel_resist_addition;
        this.atk = atk;
        this.hp = hp;
        
        PostInit();
    }

    public static monster_attr Deserializemonster_attr(JSONNode _json)
    {
        return new config.monster_attr(_json);
    }

    /// <summary>
    /// 怪物属性id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public int type { get; private set; }
    /// <summary>
    /// 模型id
    /// </summary>
    public int bookId { get; private set; }
    /// <summary>
    /// 怪物模型大小
    /// </summary>
    public int modelSize { get; private set; }
    /// <summary>
    /// 推力
    /// </summary>
    public int force { get; private set; }
    /// <summary>
    /// 移动速度
    /// </summary>
    public int speed { get; private set; }
    /// <summary>
    /// 是否转向
    /// </summary>
    public int changeDirYn { get; private set; }
    /// <summary>
    /// 质量
    /// </summary>
    public int mass { get; private set; }
    /// <summary>
    /// 击退抗性乘修
    /// </summary>
    public int repelResistAddition { get; private set; }
    /// <summary>
    /// 攻击力系数
    /// </summary>
    public int atk { get; private set; }
    /// <summary>
    /// 生命系数
    /// </summary>
    public int hp { get; private set; }
    public const int __ID__ = 82749026;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "type:" + type + ","
        + "bookId:" + bookId + ","
        + "modelSize:" + modelSize + ","
        + "force:" + force + ","
        + "speed:" + speed + ","
        + "changeDirYn:" + changeDirYn + ","
        + "mass:" + mass + ","
        + "repelResistAddition:" + repelResistAddition + ","
        + "atk:" + atk + ","
        + "hp:" + hp + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}