//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class monster_feature :  Bright.Config.BeanBase 
{
    public monster_feature(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  name = _json["name"]; }
        { if(!_json["desc"].IsString) { throw new SerializationException(); }  desc = _json["desc"]; }
        { if(!_json["para_num"].IsNumber) { throw new SerializationException(); }  paraNum = _json["para_num"]; }
        { var __json0 = _json["para"]; if(!__json0.IsArray) { throw new SerializationException(); } para = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  para.Add(__v0); }   }
        PostInit();
    }

    public monster_feature(int id, string name, string desc, int para_num, System.Collections.Generic.List<int> para ) 
    {
        this.id = id;
        this.name = name;
        this.desc = desc;
        this.paraNum = para_num;
        this.para = para;
        
        PostInit();
    }

    public static monster_feature Deserializemonster_feature(JSONNode _json)
    {
        return new config.monster_feature(_json);
    }

    /// <summary>
    /// 怪物特性id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string desc { get; private set; }
    /// <summary>
    /// 参数数量
    /// </summary>
    public int paraNum { get; private set; }
    /// <summary>
    /// 参数
    /// </summary>
    public System.Collections.Generic.List<int> para { get; private set; }
    public const int __ID__ = -439251739;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "desc:" + desc + ","
        + "paraNum:" + paraNum + ","
        + "para:" + Bright.Common.StringUtil.CollectionToString(para) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}