//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class monthly :  Bright.Config.BeanBase 
{
    public monthly(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  name = _json["name"]; }
        { var __json0 = _json["desc"]; if(!__json0.IsArray) { throw new SerializationException(); } desc = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  desc.Add(__v0); }   }
        { var __json0 = _json["desc_para"]; if(!__json0.IsArray) { throw new SerializationException(); } descPara = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  descPara.Add(__v0); }   }
        { if(!_json["pic1"].IsString) { throw new SerializationException(); }  pic1 = _json["pic1"]; }
        { if(!_json["pic2"].IsString) { throw new SerializationException(); }  pic2 = _json["pic2"]; }
        { if(!_json["pic3"].IsString) { throw new SerializationException(); }  pic3 = _json["pic3"]; }
        { if(!_json["sort"].IsNumber) { throw new SerializationException(); }  sort = _json["sort"]; }
        { var __json0 = _json["user_variable"]; if(!__json0.IsArray) { throw new SerializationException(); } userVariable = new System.Collections.Generic.List<UnityEngine.Vector2>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { UnityEngine.Vector2 __v0;  { var _json2 = __e0; if(!_json2.IsObject) { throw new SerializationException(); }  float __x; { if(!_json2["x"].IsNumber) { throw new SerializationException(); }  __x = _json2["x"]; } float __y; { if(!_json2["y"].IsNumber) { throw new SerializationException(); }  __y = _json2["y"]; } __v0 = new UnityEngine.Vector2(__x, __y); }  userVariable.Add(__v0); }   }
        { if(!_json["price"].IsNumber) { throw new SerializationException(); }  price = _json["price"]; }
        { var __json0 = _json["reward"]; if(!__json0.IsArray) { throw new SerializationException(); } reward = new System.Collections.Generic.List<UnityEngine.Vector3>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { UnityEngine.Vector3 __v0;  { var _json2 = __e0; if(!_json2.IsObject) { throw new SerializationException(); } float __x; { if(!_json2["x"].IsNumber) { throw new SerializationException(); }  __x = _json2["x"]; } float __y; { if(!_json2["y"].IsNumber) { throw new SerializationException(); }  __y = _json2["y"]; } float __z; { if(!_json2["z"].IsNumber) { throw new SerializationException(); }  __z = _json2["z"]; }  __v0 = new UnityEngine.Vector3(__x, __y,__z); }  reward.Add(__v0); }   }
        { var __json0 = _json["reward_daily"]; if(!__json0.IsArray) { throw new SerializationException(); } rewardDaily = new System.Collections.Generic.List<UnityEngine.Vector3>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { UnityEngine.Vector3 __v0;  { var _json2 = __e0; if(!_json2.IsObject) { throw new SerializationException(); } float __x; { if(!_json2["x"].IsNumber) { throw new SerializationException(); }  __x = _json2["x"]; } float __y; { if(!_json2["y"].IsNumber) { throw new SerializationException(); }  __y = _json2["y"]; } float __z; { if(!_json2["z"].IsNumber) { throw new SerializationException(); }  __z = _json2["z"]; }  __v0 = new UnityEngine.Vector3(__x, __y,__z); }  rewardDaily.Add(__v0); }   }
        PostInit();
    }

    public monthly(int id, string name, System.Collections.Generic.List<string> desc, System.Collections.Generic.List<int> desc_para, string pic1, string pic2, string pic3, int sort, System.Collections.Generic.List<UnityEngine.Vector2> user_variable, int price, System.Collections.Generic.List<UnityEngine.Vector3> reward, System.Collections.Generic.List<UnityEngine.Vector3> reward_daily ) 
    {
        this.id = id;
        this.name = name;
        this.desc = desc;
        this.descPara = desc_para;
        this.pic1 = pic1;
        this.pic2 = pic2;
        this.pic3 = pic3;
        this.sort = sort;
        this.userVariable = user_variable;
        this.price = price;
        this.reward = reward;
        this.rewardDaily = reward_daily;
        
        PostInit();
    }

    public static monthly Deserializemonthly(JSONNode _json)
    {
        return new config.monthly(_json);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string name { get; private set; }
    /// <summary>
    /// 描述文本
    /// </summary>
    public System.Collections.Generic.List<string> desc { get; private set; }
    /// <summary>
    /// 描述参数
    /// </summary>
    public System.Collections.Generic.List<int> descPara { get; private set; }
    /// <summary>
    /// 图片1(图片资源)
    /// </summary>
    public string pic1 { get; private set; }
    /// <summary>
    /// 图片2(图片资源)
    /// </summary>
    public string pic2 { get; private set; }
    /// <summary>
    /// 图片3(图片资源)
    /// </summary>
    public string pic3 { get; private set; }
    /// <summary>
    /// 显示排序
    /// </summary>
    public int sort { get; private set; }
    /// <summary>
    /// 特殊收益
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector2> userVariable { get; private set; }
    /// <summary>
    /// 价格
    /// </summary>
    public int price { get; private set; }
    /// <summary>
    /// 奖励
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> reward { get; private set; }
    /// <summary>
    /// 每日奖励
    /// </summary>
    public System.Collections.Generic.List<UnityEngine.Vector3> rewardDaily { get; private set; }
    public const int __ID__ = 853328225;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "desc:" + Bright.Common.StringUtil.CollectionToString(desc) + ","
        + "descPara:" + Bright.Common.StringUtil.CollectionToString(descPara) + ","
        + "pic1:" + pic1 + ","
        + "pic2:" + pic2 + ","
        + "pic3:" + pic3 + ","
        + "sort:" + sort + ","
        + "userVariable:" + Bright.Common.StringUtil.CollectionToString(userVariable) + ","
        + "price:" + price + ","
        + "reward:" + Bright.Common.StringUtil.CollectionToString(reward) + ","
        + "rewardDaily:" + Bright.Common.StringUtil.CollectionToString(rewardDaily) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}