//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class scene_boss :  Bright.Config.BeanBase 
{
    public scene_boss(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        { var __json0 = _json["area_size"]; if(!__json0.IsArray) { throw new SerializationException(); } areaSize = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  areaSize.Add(__v0); }   }
        { if(!_json["edge_type"].IsNumber) { throw new SerializationException(); }  edgeType = _json["edge_type"]; }
        { if(!_json["edge_width"].IsNumber) { throw new SerializationException(); }  edgeWidth = _json["edge_width"]; }
        { var __json0 = _json["edge_para"]; if(!__json0.IsArray) { throw new SerializationException(); } edgePara = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  edgePara.Add(__v0); }   }
        { var __json0 = _json["edge_module"]; if(!__json0.IsArray) { throw new SerializationException(); } edgeModule = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  edgeModule.Add(__v0); }   }
        { var __json0 = _json["event_group"]; if(!__json0.IsArray) { throw new SerializationException(); } eventGroup = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  eventGroup.Add(__v0); }   }
        { if(!_json["camera"].IsNumber) { throw new SerializationException(); }  camera = _json["camera"]; }
        { if(!_json["module_template_id"].IsNumber) { throw new SerializationException(); }  moduleTemplateId = _json["module_template_id"]; }
        { var __json0 = _json["module_template_para"]; if(!__json0.IsArray) { throw new SerializationException(); } moduleTemplatePara = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  moduleTemplatePara.Add(__v0); }   }
        PostInit();
    }

    public scene_boss(int id, System.Collections.Generic.List<int> area_size, int edge_type, int edge_width, System.Collections.Generic.List<int> edge_para, System.Collections.Generic.List<string> edge_module, System.Collections.Generic.List<int> event_group, int camera, int module_template_id, System.Collections.Generic.List<int> module_template_para ) 
    {
        this.id = id;
        this.areaSize = area_size;
        this.edgeType = edge_type;
        this.edgeWidth = edge_width;
        this.edgePara = edge_para;
        this.edgeModule = edge_module;
        this.eventGroup = event_group;
        this.camera = camera;
        this.moduleTemplateId = module_template_id;
        this.moduleTemplatePara = module_template_para;
        
        PostInit();
    }

    public static scene_boss Deserializescene_boss(JSONNode _json)
    {
        return new config.scene_boss(_json);
    }

    /// <summary>
    /// 刷新组id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 战斗区域大小
    /// </summary>
    public System.Collections.Generic.List<int> areaSize { get; private set; }
    /// <summary>
    /// 墙壁类型
    /// </summary>
    public int edgeType { get; private set; }
    /// <summary>
    /// 墙壁宽度
    /// </summary>
    public int edgeWidth { get; private set; }
    /// <summary>
    /// 墙壁参数
    /// </summary>
    public System.Collections.Generic.List<int> edgePara { get; private set; }
    /// <summary>
    /// 边缘贴图(图片资源)
    /// </summary>
    public System.Collections.Generic.List<string> edgeModule { get; private set; }
    /// <summary>
    /// 事件组
    /// </summary>
    public System.Collections.Generic.List<int> eventGroup { get; private set; }
    /// <summary>
    /// 战斗摄像机高度
    /// </summary>
    public int camera { get; private set; }
    /// <summary>
    /// 组件模版id
    /// </summary>
    public int moduleTemplateId { get; private set; }
    /// <summary>
    /// 组件模版参数
    /// </summary>
    public System.Collections.Generic.List<int> moduleTemplatePara { get; private set; }
    public const int __ID__ = -1008684692;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "areaSize:" + Bright.Common.StringUtil.CollectionToString(areaSize) + ","
        + "edgeType:" + edgeType + ","
        + "edgeWidth:" + edgeWidth + ","
        + "edgePara:" + Bright.Common.StringUtil.CollectionToString(edgePara) + ","
        + "edgeModule:" + Bright.Common.StringUtil.CollectionToString(edgeModule) + ","
        + "eventGroup:" + Bright.Common.StringUtil.CollectionToString(eventGroup) + ","
        + "camera:" + camera + ","
        + "moduleTemplateId:" + moduleTemplateId + ","
        + "moduleTemplatePara:" + Bright.Common.StringUtil.CollectionToString(moduleTemplatePara) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}