//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class skill_quality :  Bright.Config.BeanBase 
{
    public skill_quality(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  name = _json["name"]; }
        { if(!_json["pic"].IsString) { throw new SerializationException(); }  pic = _json["pic"]; }
        { if(!_json["binding_exp"].IsNumber) { throw new SerializationException(); }  bindingExp = _json["binding_exp"]; }
        { if(!_json["level_upperlimit"].IsNumber) { throw new SerializationException(); }  levelUpperlimit = _json["level_upperlimit"]; }
        { if(!_json["unlock_rank"].IsNumber) { throw new SerializationException(); }  unlockRank = _json["unlock_rank"]; }
        { if(!_json["price"].IsNumber) { throw new SerializationException(); }  price = _json["price"]; }
        PostInit();
    }

    public skill_quality(int id, string name, string pic, int binding_exp, int level_upperlimit, int unlock_rank, int price ) 
    {
        this.id = id;
        this.name = name;
        this.pic = pic;
        this.bindingExp = binding_exp;
        this.levelUpperlimit = level_upperlimit;
        this.unlockRank = unlock_rank;
        this.price = price;
        
        PostInit();
    }

    public static skill_quality Deserializeskill_quality(JSONNode _json)
    {
        return new config.skill_quality(_json);
    }

    /// <summary>
    /// 品质id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string name { get; private set; }
    /// <summary>
    /// 图片(图片资源)
    /// </summary>
    public string pic { get; private set; }
    /// <summary>
    /// 羁绊经验
    /// </summary>
    public int bindingExp { get; private set; }
    /// <summary>
    /// 等级上限
    /// </summary>
    public int levelUpperlimit { get; private set; }
    /// <summary>
    /// 解锁条件-阶级
    /// </summary>
    public int unlockRank { get; private set; }
    /// <summary>
    /// 价格
    /// </summary>
    public int price { get; private set; }
    public const int __ID__ = 1508782949;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "pic:" + pic + ","
        + "bindingExp:" + bindingExp + ","
        + "levelUpperlimit:" + levelUpperlimit + ","
        + "unlockRank:" + unlockRank + ","
        + "price:" + price + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}