//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class sweep_times :  Bright.Config.BeanBase 
{
    public sweep_times(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        { if(!_json["times"].IsNumber) { throw new SerializationException(); }  times = _json["times"]; }
        PostInit();
    }

    public sweep_times(int id, int times ) 
    {
        this.id = id;
        this.times = times;
        
        PostInit();
    }

    public static sweep_times Deserializesweep_times(JSONNode _json)
    {
        return new config.sweep_times(_json);
    }

    /// <summary>
    /// 整顿倍数id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 倍率
    /// </summary>
    public int times { get; private set; }
    public const int __ID__ = 1843863431;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "times:" + times + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}