//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class talent_level :  Bright.Config.BeanBase 
{
    public talent_level(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  name = _json["name"]; }
        { if(!_json["sort"].IsNumber) { throw new SerializationException(); }  sort = _json["sort"]; }
        PostInit();
    }

    public talent_level(int id, string name, int sort ) 
    {
        this.id = id;
        this.name = name;
        this.sort = sort;
        
        PostInit();
    }

    public static talent_level Deserializetalent_level(JSONNode _json)
    {
        return new config.talent_level(_json);
    }

    /// <summary>
    /// 天赋LevelId
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 等级名称
    /// </summary>
    public string name { get; private set; }
    /// <summary>
    /// 称号排序
    /// </summary>
    public int sort { get; private set; }
    public const int __ID__ = -1669672547;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "sort:" + sort + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}