//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class Tbart
{
    private readonly Dictionary<string, config.art> _dataMap;
    private readonly List<config.art> _dataList;
    
    public Tbart(JSONNode _json)
    {
        _dataMap = new Dictionary<string, config.art>();
        _dataList = new List<config.art>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = config.art.Deserializeart(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.artId, _v);
        }
        PostInit();
    }

    public Dictionary<string, config.art> DataMap => _dataMap;
    public List<config.art> DataList => _dataList;

    public config.art GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public config.art Get(string key) => _dataMap[key];
    public config.art this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
    
}
}