//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class Tbelement_effect
{
    private readonly List<config.element_effect> _dataList;
    

    public Tbelement_effect(JSONNode _json)
    {
        _dataList = new List<config.element_effect>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = config.element_effect.Deserializeelement_effect(_row);
            _dataList.Add(_v);
        }
        PostInit();
    }

    public List<config.element_effect> DataList => _dataList;
   



    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }

    
    partial void PostInit();
    partial void PostResolve();
    
}
}