//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class Tbenergy_shop
{
    private readonly Dictionary<int, config.energy_shop> _dataMap;
    private readonly List<config.energy_shop> _dataList;
    
    public Tbenergy_shop(JSONNode _json)
    {
        _dataMap = new Dictionary<int, config.energy_shop>();
        _dataList = new List<config.energy_shop>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = config.energy_shop.Deserializeenergy_shop(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
        PostInit();
    }

    public Dictionary<int, config.energy_shop> DataMap => _dataMap;
    public List<config.energy_shop> DataList => _dataList;

    public config.energy_shop GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public config.energy_shop Get(int key) => _dataMap[key];
    public config.energy_shop this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
    
}
}