//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class Tblanguage
{
    private readonly Dictionary<string, config.language> _dataMap;
    private readonly List<config.language> _dataList;
    
    public Tblanguage(JSONNode _json)
    {
        _dataMap = new Dictionary<string, config.language>();
        _dataList = new List<config.language>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = config.language.Deserializelanguage(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.langId, _v);
        }
        PostInit();
    }

    public Dictionary<string, config.language> DataMap => _dataMap;
    public List<config.language> DataList => _dataList;

    public config.language GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public config.language Get(string key) {if(_dataMap.TryGetValue(key,out var v)){return v;}else{UnityEngine.Debug.LogError($"当前key值不存在,请确认多语言表配置!key:{key}");var newlang = new config.language(key,key,key,key,key,key,key,key);return newlang;}}
    public config.language this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
    
    public void SwitchL10N(L10N l10N)
    {
        foreach(var v in _dataList)
        {
            switch (l10N)
            {
                case L10N.zh_cn:
                    v.current=IsEmptyStr(v.zhCn, v.langId);
                    break;
                case L10N.en:
                    v.current=IsEmptyStr(v.en, v.langId);
                    break;
                case L10N.de:
                    v.current=IsEmptyStr(v.de, v.langId);
                    break;
                case L10N.fr:
                    v.current=IsEmptyStr(v.fr, v.langId);
                    break;
                case L10N.es:
                    v.current=IsEmptyStr(v.es, v.langId);
                    break;
                case L10N.jp:
                    v.current=IsEmptyStr(v.jp, v.langId);
                    break;
            }
        }

        foreach (var v in _dataMap)
        {
            switch (l10N)
            {
                case L10N.zh_cn:
                    v.Value.current=IsEmptyStr(v.Value.zhCn, v.Value.langId);
                    break;
                case L10N.en:
                    v.Value.current=IsEmptyStr(v.Value.en, v.Value.langId);
                    break;
                case L10N.de:
                    v.Value.current=IsEmptyStr(v.Value.de, v.Value.langId);
                    break;
                case L10N.fr:
                    v.Value.current=IsEmptyStr(v.Value.fr, v.Value.langId);
                    break;
                case L10N.es:
                    v.Value.current=IsEmptyStr(v.Value.es, v.Value.langId);
                    break;
                case L10N.jp:
                    v.Value.current=IsEmptyStr(v.Value.jp, v.Value.langId);
                    break;
            }
        }
    }
    private string IsEmptyStr(string targetStr, string langid)
    {
        string current;
        if (targetStr == "")
        {
            return current = langid;
        }

        return current = targetStr;
    }
    public enum L10N
    {
        en=1,
        zh_cn=2,
        zh_HK=3,
        kr=4,
        jp=5,
        fr=6,
        de=7,
        ru=8,
        th=9,
        es=10,
    }
}
}