//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class Tbscene_module
{
    private readonly Dictionary<int, config.scene_module> _dataMap;
    private readonly List<config.scene_module> _dataList;
    
    public Tbscene_module(JSONNode _json)
    {
        _dataMap = new Dictionary<int, config.scene_module>();
        _dataList = new List<config.scene_module>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = config.scene_module.Deserializescene_module(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
        PostInit();
    }

    public Dictionary<int, config.scene_module> DataMap => _dataMap;
    public List<config.scene_module> DataList => _dataList;

    public config.scene_module GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public config.scene_module Get(int key) => _dataMap[key];
    public config.scene_module this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
    
}
}