//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class third_party :  Bright.Config.BeanBase 
{
    public third_party(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        { if(!_json["type"].IsNumber) { throw new SerializationException(); }  type = _json["type"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  name = _json["name"]; }
        { if(!_json["pic"].IsString) { throw new SerializationException(); }  pic = _json["pic"]; }
        { if(!_json["sort"].IsNumber) { throw new SerializationException(); }  sort = _json["sort"]; }
        { if(!_json["display_yn"].IsNumber) { throw new SerializationException(); }  displayYn = _json["display_yn"]; }
        PostInit();
    }

    public third_party(int id, int type, string name, string pic, int sort, int display_yn ) 
    {
        this.id = id;
        this.type = type;
        this.name = name;
        this.pic = pic;
        this.sort = sort;
        this.displayYn = display_yn;
        
        PostInit();
    }

    public static third_party Deserializethird_party(JSONNode _json)
    {
        return new config.third_party(_json);
    }

    /// <summary>
    /// 第三方id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public int type { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string name { get; private set; }
    /// <summary>
    /// 图片(图片资源)
    /// </summary>
    public string pic { get; private set; }
    /// <summary>
    /// 分享排序
    /// </summary>
    public int sort { get; private set; }
    /// <summary>
    /// 是否启用
    /// </summary>
    public int displayYn { get; private set; }
    public const int __ID__ = -822574750;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "type:" + type + ","
        + "name:" + name + ","
        + "pic:" + pic + ","
        + "sort:" + sort + ","
        + "displayYn:" + displayYn + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}