//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbachieve_group
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbachieve_group> configTbachieve_groups,Tables tables)
    { 
        configTbachieve_groups[i].id = tables.Tbachieve_group.DataList[i].id;
        var allocategroupIds =
        builder.Allocate(ref configTbachieve_groups[i].groupId,
        tables.Tbachieve_group.DataList[i].groupId.Count);
        for (var groupIds = 0; groupIds < tables.Tbachieve_group.DataList[i].groupId.Count; groupIds++)
        {
            allocategroupIds[groupIds] = tables.Tbachieve_group.DataList[i].groupId[groupIds];
        }
        configTbachieve_groups[i].name = tables.Tbachieve_group.DataList[i].name;
        configTbachieve_groups[i].icon = tables.Tbachieve_group.DataList[i].icon;
    }


    /// <summary>
    /// 成就组id
    /// </summary>
    public int id;
    /// <summary>
    /// 任务组id
    /// </summary>
    public BlobArray<int> groupId;    
    /// <summary>
    /// 名称
    /// </summary>
    public FixedString128Bytes name;
    /// <summary>
    /// 图标(图片资源)
    /// </summary>
    public FixedString128Bytes icon;
}
}