//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbachieve
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbachieve> configTbachieves,Tables tables)
    { 
        configTbachieves[i].id = tables.Tbachieve.DataList[i].id;
        configTbachieves[i].score = tables.Tbachieve.DataList[i].score;
        configTbachieves[i].name = tables.Tbachieve.DataList[i].name;
        configTbachieves[i].pic = tables.Tbachieve.DataList[i].pic;
        var allocaterewards =
        builder.Allocate(ref configTbachieves[i].reward,
        tables.Tbachieve.DataList[i].reward.Count);
        for (var rewards = 0; rewards < tables.Tbachieve.DataList[i].reward.Count; rewards++)
        {
            allocaterewards[rewards] = (int3) math.round(tables.Tbachieve.DataList[i].reward[rewards]);
        }
    }


    /// <summary>
    /// 成就等级id
    /// </summary>
    public int id;
    /// <summary>
    /// 成就点数
    /// </summary>
    public int score;
    /// <summary>
    /// 名称
    /// </summary>
    public FixedString128Bytes name;
    /// <summary>
    /// 图标(图片资源)
    /// </summary>
    public FixedString128Bytes pic;
    /// <summary>
    /// 奖励
    /// </summary>
    public BlobArray<int3> reward;  
}
}