//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbactivity
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbactivity> configTbactivitys,Tables tables)
    { 
        configTbactivitys[i].id = tables.Tbactivity.DataList[i].id;
        configTbactivitys[i].type = tables.Tbactivity.DataList[i].type;
        configTbactivitys[i].link = tables.Tbactivity.DataList[i].link;
    }


    /// <summary>
    /// ID
    /// </summary>
    public int id;
    /// <summary>
    /// 活动类型
    /// </summary>
    public int type;
    /// <summary>
    /// 关联参数
    /// </summary>
    public int link;
}
}