//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbbattleshop_drop
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbbattleshop_drop> configTbbattleshop_drops,Tables tables)
    { 
        configTbbattleshop_drops[i].assist = tables.Tbbattleshop_drop.DataList[i].assist;
        configTbbattleshop_drops[i].id = tables.Tbbattleshop_drop.DataList[i].id;
        configTbbattleshop_drops[i].quality = tables.Tbbattleshop_drop.DataList[i].quality;
        configTbbattleshop_drops[i].power = tables.Tbbattleshop_drop.DataList[i].power;
    }


    /// <summary>
    /// 辅助主键id
    /// </summary>
    public int assist;
    /// <summary>
    /// 刷新池id
    /// </summary>
    public int id;
    /// <summary>
    /// 技能品质id
    /// </summary>
    public int quality;
    /// <summary>
    /// 权重
    /// </summary>
    public int power;
}
}