//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbbattlepass_exp
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbbattlepass_exp> configTbbattlepass_exps,Tables tables)
    { 
        configTbbattlepass_exps[i].id = tables.Tbbattlepass_exp.DataList[i].id;
        configTbbattlepass_exps[i].exp = tables.Tbbattlepass_exp.DataList[i].exp;
    }


    /// <summary>
    /// 等级
    /// </summary>
    public int id;
    /// <summary>
    /// 总经验
    /// </summary>
    public int exp;
}
}