//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbbattlepass
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbbattlepass> configTbbattlepasss,Tables tables)
    { 
        configTbbattlepasss[i].id = tables.Tbbattlepass.DataList[i].id;
        configTbbattlepasss[i].name = tables.Tbbattlepass.DataList[i].name;
        configTbbattlepasss[i].bg = tables.Tbbattlepass.DataList[i].bg;
        configTbbattlepasss[i].tagFunc = tables.Tbbattlepass.DataList[i].tagFunc;
        configTbbattlepasss[i].price = tables.Tbbattlepass.DataList[i].price;
        var allocaterewardMore1s =
        builder.Allocate(ref configTbbattlepasss[i].rewardMore1,
        tables.Tbbattlepass.DataList[i].rewardMore1.Count);
        for (var rewardMore1s = 0; rewardMore1s < tables.Tbbattlepass.DataList[i].rewardMore1.Count; rewardMore1s++)
        {
            allocaterewardMore1s[rewardMore1s] = (int3) math.round(tables.Tbbattlepass.DataList[i].rewardMore1[rewardMore1s]);
        }
        var allocaterewardMore2s =
        builder.Allocate(ref configTbbattlepasss[i].rewardMore2,
        tables.Tbbattlepass.DataList[i].rewardMore2.Count);
        for (var rewardMore2s = 0; rewardMore2s < tables.Tbbattlepass.DataList[i].rewardMore2.Count; rewardMore2s++)
        {
            allocaterewardMore2s[rewardMore2s] = (int3) math.round(tables.Tbbattlepass.DataList[i].rewardMore2[rewardMore2s]);
        }
    }


    /// <summary>
    /// ID
    /// </summary>
    public int id;
    /// <summary>
    /// 名称
    /// </summary>
    public FixedString128Bytes name;
    /// <summary>
    /// 图片(图片资源)
    /// </summary>
    public FixedString128Bytes bg;
    /// <summary>
    /// 模块id
    /// </summary>
    public int tagFunc;
    /// <summary>
    /// 价格
    /// </summary>
    public int price;
    /// <summary>
    /// 更多奖励-免费线
    /// </summary>
    public BlobArray<int3> rewardMore1;  
    /// <summary>
    /// 更多奖励-付费线
    /// </summary>
    public BlobArray<int3> rewardMore2;  
}
}