//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbbattle_item
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbbattle_item> configTbbattle_items,Tables tables)
    { 
        configTbbattle_items[i].id = tables.Tbbattle_item.DataList[i].id;
        configTbbattle_items[i].model = tables.Tbbattle_item.DataList[i].model;
        configTbbattle_items[i].autoPickYn = tables.Tbbattle_item.DataList[i].autoPickYn;
        configTbbattle_items[i].pickRange = tables.Tbbattle_item.DataList[i].pickRange;
        configTbbattle_items[i].pickType = tables.Tbbattle_item.DataList[i].pickType;
        configTbbattle_items[i].type = tables.Tbbattle_item.DataList[i].type;
        var allocateeffects =
        builder.Allocate(ref configTbbattle_items[i].effect,
        tables.Tbbattle_item.DataList[i].effect.Count);
        for (var effects = 0; effects < tables.Tbbattle_item.DataList[i].effect.Count; effects++)
        {
            allocateeffects[effects] = (int3) math.round(tables.Tbbattle_item.DataList[i].effect[effects]);
        }
    }


    /// <summary>
    /// id
    /// </summary>
    public int id;
    /// <summary>
    /// 道具模型
    /// </summary>
    public FixedString128Bytes model;
    /// <summary>
    /// 是否自动拾取
    /// </summary>
    public int autoPickYn;
    /// <summary>
    /// 拾取范围
    /// </summary>
    public int pickRange;
    /// <summary>
    /// 拾取类型
    /// </summary>
    public int pickType;
    /// <summary>
    /// 道具类型
    /// </summary>
    public int type;
    /// <summary>
    /// 道具效果
    /// </summary>
    public BlobArray<int3> effect;  
}
}