//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbchapter_box
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbchapter_box> configTbchapter_boxs,Tables tables)
    { 
        configTbchapter_boxs[i].id = tables.Tbchapter_box.DataList[i].id;
        configTbchapter_boxs[i].chapterId = tables.Tbchapter_box.DataList[i].chapterId;
        configTbchapter_boxs[i].passYn = tables.Tbchapter_box.DataList[i].passYn;
        configTbchapter_boxs[i].overTime = tables.Tbchapter_box.DataList[i].overTime;
        var allocaterewards =
        builder.Allocate(ref configTbchapter_boxs[i].reward,
        tables.Tbchapter_box.DataList[i].reward.Count);
        for (var rewards = 0; rewards < tables.Tbchapter_box.DataList[i].reward.Count; rewards++)
        {
            allocaterewards[rewards] = (int3) math.round(tables.Tbchapter_box.DataList[i].reward[rewards]);
        }
        configTbchapter_boxs[i].desc = tables.Tbchapter_box.DataList[i].desc;
    }


    /// <summary>
    /// 宝箱id
    /// </summary>
    public int id;
    /// <summary>
    /// 关卡id
    /// </summary>
    public int chapterId;
    /// <summary>
    /// 是否通关
    /// </summary>
    public int passYn;
    /// <summary>
    /// 生存时间
    /// </summary>
    public int overTime;
    /// <summary>
    /// 奖励
    /// </summary>
    public BlobArray<int3> reward;  
    /// <summary>
    /// 领取描述
    /// </summary>
    public FixedString128Bytes desc;
}
}