//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbconstant
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbconstant> configTbconstants,Tables tables)
    { 
        configTbconstants[i].constantName = tables.Tbconstant.DataList[i].constantName;
        configTbconstants[i].constantValue = tables.Tbconstant.DataList[i].constantValue;
    }


    /// <summary>
    /// 宏配置名
    /// </summary>
    public FixedString128Bytes constantName;
    /// <summary>
    /// 宏配置值
    /// </summary>
    public int constantValue;
}
}