//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbdays_sign
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbdays_sign> configTbdays_signs,Tables tables)
    { 
        configTbdays_signs[i].id = tables.Tbdays_sign.DataList[i].id;
        configTbdays_signs[i].tagFunc = tables.Tbdays_sign.DataList[i].tagFunc;
        configTbdays_signs[i].name = tables.Tbdays_sign.DataList[i].name;
        configTbdays_signs[i].desc = tables.Tbdays_sign.DataList[i].desc;
        configTbdays_signs[i].pic = tables.Tbdays_sign.DataList[i].pic;
        configTbdays_signs[i].valid = tables.Tbdays_sign.DataList[i].valid;
        var allocatespecialDates =
        builder.Allocate(ref configTbdays_signs[i].specialDate,
        tables.Tbdays_sign.DataList[i].specialDate.Count);
        for (var specialDates = 0; specialDates < tables.Tbdays_sign.DataList[i].specialDate.Count; specialDates++)
        {
            allocatespecialDates[specialDates] = tables.Tbdays_sign.DataList[i].specialDate[specialDates];
        }
    }


    /// <summary>
    /// ID
    /// </summary>
    public int id;
    /// <summary>
    /// 模块id
    /// </summary>
    public int tagFunc;
    /// <summary>
    /// 名称
    /// </summary>
    public FixedString128Bytes name;
    /// <summary>
    /// 描述
    /// </summary>
    public FixedString128Bytes desc;
    /// <summary>
    /// 图片(图片资源)
    /// </summary>
    public FixedString128Bytes pic;
    /// <summary>
    /// 有效期
    /// </summary>
    public int valid;
    /// <summary>
    /// 特殊日期
    /// </summary>
    public BlobArray<int> specialDate;    
}
}