//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbdays_challenge
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbdays_challenge> configTbdays_challenges,Tables tables)
    { 
        configTbdays_challenges[i].id = tables.Tbdays_challenge.DataList[i].id;
        configTbdays_challenges[i].tagFunc = tables.Tbdays_challenge.DataList[i].tagFunc;
        configTbdays_challenges[i].desc = tables.Tbdays_challenge.DataList[i].desc;
        configTbdays_challenges[i].pic = tables.Tbdays_challenge.DataList[i].pic;
        configTbdays_challenges[i].userVariable = tables.Tbdays_challenge.DataList[i].userVariable;
        configTbdays_challenges[i].valid = tables.Tbdays_challenge.DataList[i].valid;
    }


    /// <summary>
    /// ID
    /// </summary>
    public int id;
    /// <summary>
    /// 模块id
    /// </summary>
    public int tagFunc;
    /// <summary>
    /// 描述
    /// </summary>
    public FixedString128Bytes desc;
    /// <summary>
    /// 图片(图片资源)
    /// </summary>
    public FixedString128Bytes pic;
    /// <summary>
    /// 活跃点数id
    /// </summary>
    public int userVariable;
    /// <summary>
    /// 有效期
    /// </summary>
    public int valid;
}
}