//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbdraw_banner
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbdraw_banner> configTbdraw_banners,Tables tables)
    { 
        configTbdraw_banners[i].assist = tables.Tbdraw_banner.DataList[i].assist;
        configTbdraw_banners[i].id = tables.Tbdraw_banner.DataList[i].id;
        configTbdraw_banners[i].quality = tables.Tbdraw_banner.DataList[i].quality;
        var allocateinfos =
        builder.Allocate(ref configTbdraw_banners[i].info,
        tables.Tbdraw_banner.DataList[i].info.Count);
        for (var infos = 0; infos < tables.Tbdraw_banner.DataList[i].info.Count; infos++)
        {
            allocateinfos[infos] = tables.Tbdraw_banner.DataList[i].info[infos];
        }
        configTbdraw_banners[i].power = tables.Tbdraw_banner.DataList[i].power;
    }


    /// <summary>
    /// 辅助主键id
    /// </summary>
    public int assist;
    /// <summary>
    /// bannerID
    /// </summary>
    public int id;
    /// <summary>
    /// 品质
    /// </summary>
    public int quality;
    /// <summary>
    /// 装备id
    /// </summary>
    public BlobArray<int> info;    
    /// <summary>
    /// 权重
    /// </summary>
    public int power;
}
}