//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbdrop
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbdrop> configTbdrops,Tables tables)
    { 
        configTbdrops[i].assist = tables.Tbdrop.DataList[i].assist;
        configTbdrops[i].id = tables.Tbdrop.DataList[i].id;
        configTbdrops[i].packId = tables.Tbdrop.DataList[i].packId;
        configTbdrops[i].packPower = tables.Tbdrop.DataList[i].packPower;
        var allocaterewards =
        builder.Allocate(ref configTbdrops[i].reward,
        tables.Tbdrop.DataList[i].reward.Count);
        for (var rewards = 0; rewards < tables.Tbdrop.DataList[i].reward.Count; rewards++)
        {
            allocaterewards[rewards] = (int3) math.round(tables.Tbdrop.DataList[i].reward[rewards]);
        }
    }


    /// <summary>
    /// 辅助主键id
    /// </summary>
    public int assist;
    /// <summary>
    /// 掉落组Id
    /// </summary>
    public int id;
    /// <summary>
    /// 包id
    /// </summary>
    public int packId;
    /// <summary>
    /// 包权重
    /// </summary>
    public int packPower;
    /// <summary>
    /// 获取
    /// </summary>
    public BlobArray<int3> reward;  
}
}