//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbenvironment
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbenvironment> configTbenvironments,Tables tables)
    { 
        configTbenvironments[i].id = tables.Tbenvironment.DataList[i].id;
        configTbenvironments[i].type = tables.Tbenvironment.DataList[i].type;
        configTbenvironments[i].paraNum = tables.Tbenvironment.DataList[i].paraNum;
        var allocateparas =
        builder.Allocate(ref configTbenvironments[i].para,
        tables.Tbenvironment.DataList[i].para.Count);
        for (var paras = 0; paras < tables.Tbenvironment.DataList[i].para.Count; paras++)
        {
            allocateparas[paras] = tables.Tbenvironment.DataList[i].para[paras];
        }
        configTbenvironments[i].bossParaNum = tables.Tbenvironment.DataList[i].bossParaNum;
        var allocatebossParas =
        builder.Allocate(ref configTbenvironments[i].bossPara,
        tables.Tbenvironment.DataList[i].bossPara.Count);
        for (var bossParas = 0; bossParas < tables.Tbenvironment.DataList[i].bossPara.Count; bossParas++)
        {
            allocatebossParas[bossParas] = tables.Tbenvironment.DataList[i].bossPara[bossParas];
        }
    }


    /// <summary>
    /// 环境id
    /// </summary>
    public int id;
    /// <summary>
    /// 类型
    /// </summary>
    public int type;
    /// <summary>
    /// 参数数量
    /// </summary>
    public int paraNum;
    /// <summary>
    /// 参数
    /// </summary>
    public BlobArray<int> para;    
    /// <summary>
    /// boss场景参数数量
    /// </summary>
    public int bossParaNum;
    /// <summary>
    /// boss场景参数
    /// </summary>
    public BlobArray<int> bossPara;    
}
}