//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbequip_quality
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbequip_quality> configTbequip_qualitys,Tables tables)
    { 
        configTbequip_qualitys[i].id = tables.Tbequip_quality.DataList[i].id;
        configTbequip_qualitys[i].type = tables.Tbequip_quality.DataList[i].type;
        configTbequip_qualitys[i].subtype = tables.Tbequip_quality.DataList[i].subtype;
        configTbequip_qualitys[i].levelMax = tables.Tbequip_quality.DataList[i].levelMax;
        configTbequip_qualitys[i].iconSign = tables.Tbequip_quality.DataList[i].iconSign;
        configTbequip_qualitys[i].signNum = tables.Tbequip_quality.DataList[i].signNum;
        var allocatemergeRules =
        builder.Allocate(ref configTbequip_qualitys[i].mergeRule,
        tables.Tbequip_quality.DataList[i].mergeRule.Count);
        for (var mergeRules = 0; mergeRules < tables.Tbequip_quality.DataList[i].mergeRule.Count; mergeRules++)
        {
            allocatemergeRules[mergeRules] = tables.Tbequip_quality.DataList[i].mergeRule[mergeRules];
        }
        configTbequip_qualitys[i].mergeSelf = tables.Tbequip_quality.DataList[i].mergeSelf;
        configTbequip_qualitys[i].valueIndex = tables.Tbequip_quality.DataList[i].valueIndex;
    }


    /// <summary>
    /// 品质Id
    /// </summary>
    public int id;
    /// <summary>
    /// 品质大类
    /// </summary>
    public int type;
    /// <summary>
    /// 品质子类
    /// </summary>
    public int subtype;
    /// <summary>
    /// 等级上限
    /// </summary>
    public int levelMax;
    /// <summary>
    /// 角标图片(图片资源)
    /// </summary>
    public FixedString128Bytes iconSign;
    /// <summary>
    /// 数字角标
    /// </summary>
    public int signNum;
    /// <summary>
    /// 合成需求
    /// </summary>
    public BlobArray<int> mergeRule;    
    /// <summary>
    /// 合成材料是否需要与自身ID相同
    /// </summary>
    public int mergeSelf;
    /// <summary>
    /// 价值指数
    /// </summary>
    public int valueIndex;
}
}