//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTberrorcode
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTberrorcode> configTberrorcodes,Tables tables)
    { 
        configTberrorcodes[i].id = tables.Tberrorcode.DataList[i].id;
        configTberrorcodes[i].name = tables.Tberrorcode.DataList[i].name;
    }


    /// <summary>
    /// 错误码id
    /// </summary>
    public int id;
    /// <summary>
    /// 错误码提示
    /// </summary>
    public FixedString128Bytes name;
}
}