//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbevent_type
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbevent_type> configTbevent_types,Tables tables)
    { 
        configTbevent_types[i].id = tables.Tbevent_type.DataList[i].id;
        configTbevent_types[i].eventType = tables.Tbevent_type.DataList[i].eventType;
        configTbevent_types[i].timeLimit = tables.Tbevent_type.DataList[i].timeLimit;
    }


    /// <summary>
    /// 类型id
    /// </summary>
    public int id;
    /// <summary>
    /// 作用方类型
    /// </summary>
    public int eventType;
    /// <summary>
    /// 生命周期
    /// </summary>
    public int timeLimit;
}
}