//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbfr
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbfr> configTbfrs,Tables tables)
    { 
        configTbfrs[i].id = tables.Tbfr.DataList[i].id;
        configTbfrs[i].name = tables.Tbfr.DataList[i].name;
        configTbfrs[i].pic = tables.Tbfr.DataList[i].pic;
        configTbfrs[i].desc = tables.Tbfr.DataList[i].desc;
        var allocaterewards =
        builder.Allocate(ref configTbfrs[i].reward,
        tables.Tbfr.DataList[i].reward.Count);
        for (var rewards = 0; rewards < tables.Tbfr.DataList[i].reward.Count; rewards++)
        {
            allocaterewards[rewards] = (int3) math.round(tables.Tbfr.DataList[i].reward[rewards]);
        }
        configTbfrs[i].goto0 = tables.Tbfr.DataList[i].goto0;
    }


    /// <summary>
    /// id
    /// </summary>
    public int id;
    /// <summary>
    /// 名称
    /// </summary>
    public FixedString128Bytes name;
    /// <summary>
    /// 图片(图片资源)
    /// </summary>
    public FixedString128Bytes pic;
    /// <summary>
    /// 描述
    /// </summary>
    public FixedString128Bytes desc;
    /// <summary>
    /// 奖励
    /// </summary>
    public BlobArray<int3> reward;  
    /// <summary>
    /// 跳转
    /// </summary>
    public int goto0;
}
}