//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbgift_group
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbgift_group> configTbgift_groups,Tables tables)
    { 
        configTbgift_groups[i].id = tables.Tbgift_group.DataList[i].id;
        configTbgift_groups[i].tagFunc = tables.Tbgift_group.DataList[i].tagFunc;
        configTbgift_groups[i].name = tables.Tbgift_group.DataList[i].name;
        configTbgift_groups[i].pic = tables.Tbgift_group.DataList[i].pic;
        configTbgift_groups[i].valid = tables.Tbgift_group.DataList[i].valid;
    }


    /// <summary>
    /// ID
    /// </summary>
    public int id;
    /// <summary>
    /// 所属模块id
    /// </summary>
    public int tagFunc;
    /// <summary>
    /// 名称
    /// </summary>
    public FixedString128Bytes name;
    /// <summary>
    /// 图片(图片资源)
    /// </summary>
    public FixedString128Bytes pic;
    /// <summary>
    /// 有效期
    /// </summary>
    public int valid;
}
}