//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbgoods
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbgoods> configTbgoodss,Tables tables)
    { 
        configTbgoodss[i].id = tables.Tbgoods.DataList[i].id;
        configTbgoodss[i].num = tables.Tbgoods.DataList[i].num;
        configTbgoodss[i].table = tables.Tbgoods.DataList[i].table;
        configTbgoodss[i].idField = tables.Tbgoods.DataList[i].idField;
        configTbgoodss[i].priceField = tables.Tbgoods.DataList[i].priceField;
    }


    /// <summary>
    /// id
    /// </summary>
    public int id;
    /// <summary>
    /// 商品编码
    /// </summary>
    public FixedString128Bytes num;
    /// <summary>
    /// 商品表
    /// </summary>
    public FixedString128Bytes table;
    /// <summary>
    /// ID字段
    /// </summary>
    public FixedString128Bytes idField;
    /// <summary>
    /// 价格字段
    /// </summary>
    public FixedString128Bytes priceField;
}
}