//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbHeroBox
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbHeroBox> configTbHeroBoxs,Tables tables)
    { 
        configTbHeroBoxs[i].id = tables.TbHeroBox.DataList[i].id;
        configTbHeroBoxs[i].time = tables.TbHeroBox.DataList[i].time;
        configTbHeroBoxs[i].name = tables.TbHeroBox.DataList[i].name;
        configTbHeroBoxs[i].desc = tables.TbHeroBox.DataList[i].desc;
        configTbHeroBoxs[i].icon = tables.TbHeroBox.DataList[i].icon;
        configTbHeroBoxs[i].sort = tables.TbHeroBox.DataList[i].sort;
        configTbHeroBoxs[i].price1 = tables.TbHeroBox.DataList[i].price1;
        configTbHeroBoxs[i].price2 = tables.TbHeroBox.DataList[i].price2;
        var allocatepowers =
        builder.Allocate(ref configTbHeroBoxs[i].power,
        tables.TbHeroBox.DataList[i].power.Count);
        for (var powers = 0; powers < tables.TbHeroBox.DataList[i].power.Count; powers++)
        {
            allocatepowers[powers] = (int2) math.round(tables.TbHeroBox.DataList[i].power[powers]);
        }
        configTbHeroBoxs[i].ensureCount = tables.TbHeroBox.DataList[i].ensureCount;
    }


    /// <summary>
    /// ID
    /// </summary>
    public int id;
    /// <summary>
    /// time
    /// </summary>
    public int time;
    /// <summary>
    /// 名称
    /// </summary>
    public FixedString128Bytes name;
    /// <summary>
    /// 描述
    /// </summary>
    public FixedString128Bytes desc;
    /// <summary>
    /// 图标
    /// </summary>
    public FixedString128Bytes icon;
    /// <summary>
    /// 排序
    /// </summary>
    public int sort;
    /// <summary>
    /// 价格
    /// </summary>
    public int price1;
    /// <summary>
    /// 价格
    /// </summary>
    public int price2;
    /// <summary>
    /// 十连抽
    /// </summary>
    public BlobArray<int2> power;  
    /// <summary>
    /// 保底数
    /// </summary>
    public int ensureCount;
}
}