//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbheroBox
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbheroBox> configTbheroBoxs,Tables tables)
    { 
        configTbheroBoxs[i].id = tables.TbheroBox.DataList[i].id;
        configTbheroBoxs[i].time = tables.TbheroBox.DataList[i].time;
        configTbheroBoxs[i].name = tables.TbheroBox.DataList[i].name;
        configTbheroBoxs[i].desc = tables.TbheroBox.DataList[i].desc;
        configTbheroBoxs[i].icon = tables.TbheroBox.DataList[i].icon;
        configTbheroBoxs[i].sort = tables.TbheroBox.DataList[i].sort;
        configTbheroBoxs[i].price1 = tables.TbheroBox.DataList[i].price1;
        configTbheroBoxs[i].price2 = tables.TbheroBox.DataList[i].price2;
    }


    /// <summary>
    /// ID
    /// </summary>
    public int id;
    /// <summary>
    /// time
    /// </summary>
    public int time;
    /// <summary>
    /// 名称
    /// </summary>
    public FixedString128Bytes name;
    /// <summary>
    /// 描述
    /// </summary>
    public FixedString128Bytes desc;
    /// <summary>
    /// 图标
    /// </summary>
    public FixedString128Bytes icon;
    /// <summary>
    /// 排序
    /// </summary>
    public int sort;
    /// <summary>
    /// 价格
    /// </summary>
    public int price1;
    /// <summary>
    /// 价格
    /// </summary>
    public int price2;
}
}