//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTblanguage
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTblanguage> configTblanguages,Tables tables)
    { 
        configTblanguages[i].langId = tables.Tblanguage.DataList[i].langId;
        configTblanguages[i].zhCn = tables.Tblanguage.DataList[i].zhCn;
        configTblanguages[i].en = tables.Tblanguage.DataList[i].en;
        configTblanguages[i].de = tables.Tblanguage.DataList[i].de;
        configTblanguages[i].fr = tables.Tblanguage.DataList[i].fr;
        configTblanguages[i].es = tables.Tblanguage.DataList[i].es;
        configTblanguages[i].jp = tables.Tblanguage.DataList[i].jp;
        configTblanguages[i].current = tables.Tblanguage.DataList[i].current;
    }


    /// <summary>
    /// key
    /// </summary>
    public FixedString512Bytes langId;
    /// <summary>
    /// 简体中文
    /// </summary>
    public FixedString512Bytes zhCn;
    /// <summary>
    /// 英文
    /// </summary>
    public FixedString512Bytes en;
    /// <summary>
    /// 德语
    /// </summary>
    public FixedString512Bytes de;
    /// <summary>
    /// 法语
    /// </summary>
    public FixedString512Bytes fr;
    /// <summary>
    /// 西班牙
    /// </summary>
    public FixedString512Bytes es;
    /// <summary>
    /// 日语
    /// </summary>
    public FixedString512Bytes jp;
    /// <summary>
    /// 当前语言
    /// </summary>
    public FixedString512Bytes current;
}
}