//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbmodule_template
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbmodule_template> configTbmodule_templates,Tables tables)
    { 
        configTbmodule_templates[i].assist = tables.Tbmodule_template.DataList[i].assist;
        configTbmodule_templates[i].id = tables.Tbmodule_template.DataList[i].id;
        configTbmodule_templates[i].ruleId = tables.Tbmodule_template.DataList[i].ruleId;
        configTbmodule_templates[i].time = tables.Tbmodule_template.DataList[i].time;
        configTbmodule_templates[i].num = tables.Tbmodule_template.DataList[i].num;
    }


    /// <summary>
    /// 辅助主键id
    /// </summary>
    public int assist;
    /// <summary>
    /// 刷新组id
    /// </summary>
    public int id;
    /// <summary>
    /// 组规则id
    /// </summary>
    public int ruleId;
    /// <summary>
    /// 刷新时间
    /// </summary>
    public int time;
    /// <summary>
    /// 刷新规则数量
    /// </summary>
    public int num;
}
}