//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbmonopoly
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbmonopoly> configTbmonopolys,Tables tables)
    { 
        configTbmonopolys[i].id = tables.Tbmonopoly.DataList[i].id;
        configTbmonopolys[i].tagFunc = tables.Tbmonopoly.DataList[i].tagFunc;
        configTbmonopolys[i].desc = tables.Tbmonopoly.DataList[i].desc;
        configTbmonopolys[i].pic = tables.Tbmonopoly.DataList[i].pic;
        configTbmonopolys[i].shopPic = tables.Tbmonopoly.DataList[i].shopPic;
        configTbmonopolys[i].taskPic = tables.Tbmonopoly.DataList[i].taskPic;
        configTbmonopolys[i].diceItem = tables.Tbmonopoly.DataList[i].diceItem;
        configTbmonopolys[i].bugDiceYn = tables.Tbmonopoly.DataList[i].bugDiceYn;
        configTbmonopolys[i].shopItem = tables.Tbmonopoly.DataList[i].shopItem;
        configTbmonopolys[i].monopolyShop = tables.Tbmonopoly.DataList[i].monopolyShop;
    }


    /// <summary>
    /// id
    /// </summary>
    public int id;
    /// <summary>
    /// 所属模块id
    /// </summary>
    public int tagFunc;
    /// <summary>
    /// 详情
    /// </summary>
    public FixedString128Bytes desc;
    /// <summary>
    /// 图片(图片资源)
    /// </summary>
    public FixedString128Bytes pic;
    /// <summary>
    /// 兑换商店图片(图片资源)
    /// </summary>
    public FixedString128Bytes shopPic;
    /// <summary>
    /// 任务图片(图片资源)
    /// </summary>
    public FixedString128Bytes taskPic;
    /// <summary>
    /// 骰子道具id
    /// </summary>
    public int diceItem;
    /// <summary>
    /// 是否能够购买骰子
    /// </summary>
    public int bugDiceYn;
    /// <summary>
    /// 兑换道具id
    /// </summary>
    public int shopItem;
    /// <summary>
    /// 兑换列表
    /// </summary>
    public int monopolyShop;
}
}