//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbmonopoly_event
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbmonopoly_event> configTbmonopoly_events,Tables tables)
    { 
        configTbmonopoly_events[i].id = tables.Tbmonopoly_event.DataList[i].id;
        configTbmonopoly_events[i].pic = tables.Tbmonopoly_event.DataList[i].pic;
    }


    /// <summary>
    /// 事件id
    /// </summary>
    public int id;
    /// <summary>
    /// 图片(图片资源)
    /// </summary>
    public FixedString128Bytes pic;
}
}