//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbmonster_feature
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbmonster_feature> configTbmonster_features,Tables tables)
    { 
        configTbmonster_features[i].id = tables.Tbmonster_feature.DataList[i].id;
        configTbmonster_features[i].name = tables.Tbmonster_feature.DataList[i].name;
        configTbmonster_features[i].desc = tables.Tbmonster_feature.DataList[i].desc;
        configTbmonster_features[i].paraNum = tables.Tbmonster_feature.DataList[i].paraNum;
        var allocateparas =
        builder.Allocate(ref configTbmonster_features[i].para,
        tables.Tbmonster_feature.DataList[i].para.Count);
        for (var paras = 0; paras < tables.Tbmonster_feature.DataList[i].para.Count; paras++)
        {
            allocateparas[paras] = tables.Tbmonster_feature.DataList[i].para[paras];
        }
    }


    /// <summary>
    /// 怪物特性id
    /// </summary>
    public int id;
    /// <summary>
    /// 名称
    /// </summary>
    public FixedString128Bytes name;
    /// <summary>
    /// 描述
    /// </summary>
    public FixedString128Bytes desc;
    /// <summary>
    /// 参数数量
    /// </summary>
    public int paraNum;
    /// <summary>
    /// 参数
    /// </summary>
    public BlobArray<int> para;    
}
}