//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbMonthCard
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbMonthCard> configTbMonthCards,Tables tables)
    { 
        configTbMonthCards[i].id = tables.TbMonthCard.DataList[i].id;
        configTbMonthCards[i].time = tables.TbMonthCard.DataList[i].time;
        configTbMonthCards[i].name = tables.TbMonthCard.DataList[i].name;
        var allocatedescparas =
        builder.Allocate(ref configTbMonthCards[i].descpara,
        tables.TbMonthCard.DataList[i].descpara.Count);
        for (var descparas = 0; descparas < tables.TbMonthCard.DataList[i].descpara.Count; descparas++)
        {
            allocatedescparas[descparas] = (int2) math.round(tables.TbMonthCard.DataList[i].descpara[descparas]);
        }
        var allocatedescs =
        builder.Allocate(ref configTbMonthCards[i].desc,
        tables.TbMonthCard.DataList[i].desc.Count);
        for (var descs = 0; descs < tables.TbMonthCard.DataList[i].desc.Count; descs++)
        {
            allocatedescs[descs] = tables.TbMonthCard.DataList[i].desc[descs];
        }
        configTbMonthCards[i].icon = tables.TbMonthCard.DataList[i].icon;
        configTbMonthCards[i].sort = tables.TbMonthCard.DataList[i].sort;
        configTbMonthCards[i].price = tables.TbMonthCard.DataList[i].price;
    }


    /// <summary>
    /// ID
    /// </summary>
    public int id;
    /// <summary>
    /// time
    /// </summary>
    public int time;
    /// <summary>
    /// 名称
    /// </summary>
    public FixedString128Bytes name;
    /// <summary>
    /// 描述
    /// </summary>
    public BlobArray<int2> descpara;  
    /// <summary>
    /// 描述
    /// </summary>
    public BlobArray<FixedString128Bytes> desc;  
    /// <summary>
    /// 图标
    /// </summary>
    public FixedString128Bytes icon;
    /// <summary>
    /// 排序
    /// </summary>
    public int sort;
    /// <summary>
    /// 价格
    /// </summary>
    public int price;
}
}