//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbplayer_role
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbplayer_role> configTbplayer_roles,Tables tables)
    { 
        configTbplayer_roles[i].id = tables.Tbplayer_role.DataList[i].id;
    }


    /// <summary>
    /// 角色id
    /// </summary>
    public int id;
}
}