//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbquality
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbquality> configTbqualitys,Tables tables)
    { 
        configTbqualitys[i].id = tables.Tbquality.DataList[i].id;
        configTbqualitys[i].name = tables.Tbquality.DataList[i].name;
        configTbqualitys[i].frame = tables.Tbquality.DataList[i].frame;
        configTbqualitys[i].fontColor = tables.Tbquality.DataList[i].fontColor;
        var allocatetoequips =
        builder.Allocate(ref configTbqualitys[i].toequip,
        tables.Tbquality.DataList[i].toequip.Count);
        for (var toequips = 0; toequips < tables.Tbquality.DataList[i].toequip.Count; toequips++)
        {
            allocatetoequips[toequips] = tables.Tbquality.DataList[i].toequip[toequips];
        }
        configTbqualitys[i].numFrame = tables.Tbquality.DataList[i].numFrame;
        configTbqualitys[i].posFrame = tables.Tbquality.DataList[i].posFrame;
        configTbqualitys[i].unlock = tables.Tbquality.DataList[i].unlock;
        configTbqualitys[i].lock0 = tables.Tbquality.DataList[i].lock0;
    }


    /// <summary>
    /// 品质id
    /// </summary>
    public int id;
    /// <summary>
    /// 名称
    /// </summary>
    public FixedString128Bytes name;
    /// <summary>
    /// 品质框(图片资源)
    /// </summary>
    public FixedString128Bytes frame;
    /// <summary>
    /// 品质字体颜色
    /// </summary>
    public FixedString128Bytes fontColor;
    /// <summary>
    /// 装备数据表
    /// </summary>
    public BlobArray<int> toequip;    
    /// <summary>
    /// 角标框(图片资源)
    /// </summary>
    public FixedString128Bytes numFrame;
    /// <summary>
    /// 部位底板(图片资源)
    /// </summary>
    public FixedString128Bytes posFrame;
    /// <summary>
    /// 技能解锁图标(图片资源)
    /// </summary>
    public FixedString128Bytes unlock;
    /// <summary>
    /// 技能未解锁图标(图片资源)
    /// </summary>
    public FixedString128Bytes lock0;
}
}