//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbracist
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbracist> configTbracists,Tables tables)
    { 
        configTbracists[i].id = tables.Tbracist.DataList[i].id;
        configTbracists[i].name = tables.Tbracist.DataList[i].name;
    }


    /// <summary>
    /// id
    /// </summary>
    public int id;
    /// <summary>
    /// 名称
    /// </summary>
    public FixedString128Bytes name;
}
}