//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbsetting
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbsetting> configTbsettings,Tables tables)
    { 
        configTbsettings[i].id = tables.Tbsetting.DataList[i].id;
        configTbsettings[i].name = tables.Tbsetting.DataList[i].name;
        configTbsettings[i].pic1 = tables.Tbsetting.DataList[i].pic1;
        configTbsettings[i].pic2 = tables.Tbsetting.DataList[i].pic2;
        configTbsettings[i].sort = tables.Tbsetting.DataList[i].sort;
        configTbsettings[i].init = tables.Tbsetting.DataList[i].init;
    }


    /// <summary>
    /// 设置id
    /// </summary>
    public int id;
    /// <summary>
    /// 名称
    /// </summary>
    public FixedString128Bytes name;
    /// <summary>
    /// 图片(开启)(图片资源)
    /// </summary>
    public FixedString128Bytes pic1;
    /// <summary>
    /// 图片(关闭)(图片资源)
    /// </summary>
    public FixedString128Bytes pic2;
    /// <summary>
    /// 排序
    /// </summary>
    public int sort;
    /// <summary>
    /// 默认值
    /// </summary>
    public int init;
}
}