//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbsign_acc
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbsign_acc> configTbsign_accs,Tables tables)
    { 
        configTbsign_accs[i].id = tables.Tbsign_acc.DataList[i].id;
        configTbsign_accs[i].day = tables.Tbsign_acc.DataList[i].day;
        var allocaterewards =
        builder.Allocate(ref configTbsign_accs[i].reward,
        tables.Tbsign_acc.DataList[i].reward.Count);
        for (var rewards = 0; rewards < tables.Tbsign_acc.DataList[i].reward.Count; rewards++)
        {
            allocaterewards[rewards] = (int3) math.round(tables.Tbsign_acc.DataList[i].reward[rewards]);
        }
    }


    /// <summary>
    /// 宝箱id
    /// </summary>
    public int id;
    /// <summary>
    /// 所需天数
    /// </summary>
    public int day;
    /// <summary>
    /// 奖励
    /// </summary>
    public BlobArray<int3> reward;  
}
}