//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbskill_quality
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbskill_quality> configTbskill_qualitys,Tables tables)
    { 
        configTbskill_qualitys[i].id = tables.Tbskill_quality.DataList[i].id;
        configTbskill_qualitys[i].name = tables.Tbskill_quality.DataList[i].name;
        configTbskill_qualitys[i].pic = tables.Tbskill_quality.DataList[i].pic;
        configTbskill_qualitys[i].bindingExp = tables.Tbskill_quality.DataList[i].bindingExp;
        configTbskill_qualitys[i].levelUpperlimit = tables.Tbskill_quality.DataList[i].levelUpperlimit;
        configTbskill_qualitys[i].unlockRank = tables.Tbskill_quality.DataList[i].unlockRank;
        configTbskill_qualitys[i].price = tables.Tbskill_quality.DataList[i].price;
    }


    /// <summary>
    /// 品质id
    /// </summary>
    public int id;
    /// <summary>
    /// 名称
    /// </summary>
    public FixedString128Bytes name;
    /// <summary>
    /// 图片(图片资源)
    /// </summary>
    public FixedString128Bytes pic;
    /// <summary>
    /// 羁绊经验
    /// </summary>
    public int bindingExp;
    /// <summary>
    /// 等级上限
    /// </summary>
    public int levelUpperlimit;
    /// <summary>
    /// 解锁条件-阶级
    /// </summary>
    public int unlockRank;
    /// <summary>
    /// 价格
    /// </summary>
    public int price;
}
}