//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbspecial_effect_movement
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbspecial_effect_movement> configTbspecial_effect_movements,Tables tables)
    { 
        configTbspecial_effect_movements[i].id = tables.Tbspecial_effect_movement.DataList[i].id;
        configTbspecial_effect_movements[i].type = tables.Tbspecial_effect_movement.DataList[i].type;
        configTbspecial_effect_movements[i].para1 = tables.Tbspecial_effect_movement.DataList[i].para1;
        configTbspecial_effect_movements[i].para2 = tables.Tbspecial_effect_movement.DataList[i].para2;
        configTbspecial_effect_movements[i].para3 = tables.Tbspecial_effect_movement.DataList[i].para3;
        configTbspecial_effect_movements[i].para4 = tables.Tbspecial_effect_movement.DataList[i].para4;
    }


    /// <summary>
    /// id
    /// </summary>
    public int id;
    /// <summary>
    /// 类型
    /// </summary>
    public int type;
    /// <summary>
    /// 参数1
    /// </summary>
    public int para1;
    /// <summary>
    /// 参数2
    /// </summary>
    public int para2;
    /// <summary>
    /// 参数3
    /// </summary>
    public int para3;
    /// <summary>
    /// 参数4
    /// </summary>
    public int para4;
}
}