//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbspecials
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbspecials> configTbspecialss,Tables tables)
    { 
        configTbspecialss[i].id = tables.Tbspecials.DataList[i].id;
        configTbspecialss[i].type = tables.Tbspecials.DataList[i].type;
        var allocatefreeRules =
        builder.Allocate(ref configTbspecialss[i].freeRule,
        tables.Tbspecials.DataList[i].freeRule.Count);
        for (var freeRules = 0; freeRules < tables.Tbspecials.DataList[i].freeRule.Count; freeRules++)
        {
            allocatefreeRules[freeRules] = (int2) math.round(tables.Tbspecials.DataList[i].freeRule[freeRules]);
        }
        configTbspecialss[i].price = tables.Tbspecials.DataList[i].price;
        configTbspecialss[i].ratio = tables.Tbspecials.DataList[i].ratio;
        var allocaterewards =
        builder.Allocate(ref configTbspecialss[i].reward,
        tables.Tbspecials.DataList[i].reward.Count);
        for (var rewards = 0; rewards < tables.Tbspecials.DataList[i].reward.Count; rewards++)
        {
            allocaterewards[rewards] = (int3) math.round(tables.Tbspecials.DataList[i].reward[rewards]);
        }
        configTbspecialss[i].sort = tables.Tbspecials.DataList[i].sort;
    }


    /// <summary>
    /// ID
    /// </summary>
    public int id;
    /// <summary>
    /// 类型
    /// </summary>
    public int type;
    /// <summary>
    /// 免费规则
    /// </summary>
    public BlobArray<int2> freeRule;  
    /// <summary>
    /// 价格档位
    /// </summary>
    public int price;
    /// <summary>
    /// 返利比
    /// </summary>
    public int ratio;
    /// <summary>
    /// 奖励
    /// </summary>
    public BlobArray<int3> reward;  
    /// <summary>
    /// 排序
    /// </summary>
    public int sort;
}
}