//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbtalent_level
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbtalent_level> configTbtalent_levels,Tables tables)
    { 
        configTbtalent_levels[i].id = tables.Tbtalent_level.DataList[i].id;
        configTbtalent_levels[i].name = tables.Tbtalent_level.DataList[i].name;
        configTbtalent_levels[i].sort = tables.Tbtalent_level.DataList[i].sort;
    }


    /// <summary>
    /// 天赋LevelId
    /// </summary>
    public int id;
    /// <summary>
    /// 等级名称
    /// </summary>
    public FixedString128Bytes name;
    /// <summary>
    /// 称号排序
    /// </summary>
    public int sort;
}
}