//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbtalent
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbtalent> configTbtalents,Tables tables)
    { 
        configTbtalents[i].id = tables.Tbtalent.DataList[i].id;
        configTbtalents[i].type = tables.Tbtalent.DataList[i].type;
        configTbtalents[i].preId = tables.Tbtalent.DataList[i].preId;
        configTbtalents[i].name = tables.Tbtalent.DataList[i].name;
        var allocateparas =
        builder.Allocate(ref configTbtalents[i].para,
        tables.Tbtalent.DataList[i].para.Count);
        for (var paras = 0; paras < tables.Tbtalent.DataList[i].para.Count; paras++)
        {
            allocateparas[paras] = tables.Tbtalent.DataList[i].para[paras];
        }
        configTbtalents[i].desc = tables.Tbtalent.DataList[i].desc;
        configTbtalents[i].icon = tables.Tbtalent.DataList[i].icon;
        configTbtalents[i].level = tables.Tbtalent.DataList[i].level;
        var allocatecosts =
        builder.Allocate(ref configTbtalents[i].cost,
        tables.Tbtalent.DataList[i].cost.Count);
        for (var costs = 0; costs < tables.Tbtalent.DataList[i].cost.Count; costs++)
        {
            allocatecosts[costs] = (int3) math.round(tables.Tbtalent.DataList[i].cost[costs]);
        }
        configTbtalents[i].animation = tables.Tbtalent.DataList[i].animation;
    }


    /// <summary>
    /// 天赋Id
    /// </summary>
    public int id;
    /// <summary>
    /// 类型
    /// </summary>
    public int type;
    /// <summary>
    /// 前置天赋
    /// </summary>
    public int preId;
    /// <summary>
    /// 名称
    /// </summary>
    public FixedString128Bytes name;
    /// <summary>
    /// 参数值
    /// </summary>
    public BlobArray<int> para;    
    /// <summary>
    /// 描述
    /// </summary>
    public FixedString128Bytes desc;
    /// <summary>
    /// 图标(图片资源)
    /// </summary>
    public FixedString128Bytes icon;
    /// <summary>
    /// 等级
    /// </summary>
    public int level;
    /// <summary>
    /// 消耗
    /// </summary>
    public BlobArray<int3> cost;  
    /// <summary>
    /// 动画名称
    /// </summary>
    public FixedString128Bytes animation;
}
}