//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbachieve_groups
{
    public BlobArray<ConfigTbachieve_group> configTbachieve_groups;

    public ref ConfigTbachieve_group Get(int id)
    {
        for (int i = 0; i < configTbachieve_groups.Length; i++)
        {
            if (configTbachieve_groups[i].id == id)
            {
                return ref configTbachieve_groups[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbachieve_group,Check Config Plz!");
        return ref configTbachieve_groups[0];
    }

}
}