//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbachieves
{
    public BlobArray<ConfigTbachieve> configTbachieves;

    public ref ConfigTbachieve Get(int id)
    {
        for (int i = 0; i < configTbachieves.Length; i++)
        {
            if (configTbachieves[i].id == id)
            {
                return ref configTbachieves[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbachieve,Check Config Plz!");
        return ref configTbachieves[0];
    }

}
}