//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbannounces
{
    public BlobArray<ConfigTbannounce> configTbannounces;

    public ref ConfigTbannounce Get(int id)
    {
        for (int i = 0; i < configTbannounces.Length; i++)
        {
            if (configTbannounces[i].id == id)
            {
                return ref configTbannounces[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbannounce,Check Config Plz!");
        return ref configTbannounces[0];
    }

}
}