//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbanecdotes
{
    public BlobArray<ConfigTbanecdote> configTbanecdotes;

    public ref ConfigTbanecdote Get(int id)
    {
        for (int i = 0; i < configTbanecdotes.Length; i++)
        {
            if (configTbanecdotes[i].id == id)
            {
                return ref configTbanecdotes[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbanecdote,Check Config Plz!");
        return ref configTbanecdotes[0];
    }

}
}