//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbarts
{
    public BlobArray<ConfigTbart> configTbarts;

    public ref ConfigTbart Get(string id)
    {
        for (int i = 0; i < configTbarts.Length; i++)
        {
            if (configTbarts[i].artId == id)
            {
                return ref configTbarts[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->artId:{id} in Tbart,Check Config Plz!");
        return ref configTbarts[0];
    }

}
}