//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbattr_variables
{
    public BlobArray<ConfigTbattr_variable> configTbattr_variables;

    public ref ConfigTbattr_variable Get(int id)
    {
        for (int i = 0; i < configTbattr_variables.Length; i++)
        {
            if (configTbattr_variables[i].id == id)
            {
                return ref configTbattr_variables[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbattr_variable,Check Config Plz!");
        return ref configTbattr_variables[0];
    }

}
}