//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbbattlepasss
{
    public BlobArray<ConfigTbbattlepass> configTbbattlepasss;

    public ref ConfigTbbattlepass Get(int id)
    {
        for (int i = 0; i < configTbbattlepasss.Length; i++)
        {
            if (configTbbattlepasss[i].id == id)
            {
                return ref configTbbattlepasss[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbbattlepass,Check Config Plz!");
        return ref configTbbattlepasss[0];
    }

}
}