//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbbattle_constants
{
    public BlobArray<ConfigTbbattle_constant> configTbbattle_constants;

    public ref ConfigTbbattle_constant Get(string id)
    {
        for (int i = 0; i < configTbbattle_constants.Length; i++)
        {
            if (configTbbattle_constants[i].constantName == id)
            {
                return ref configTbbattle_constants[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->constantName:{id} in Tbbattle_constant,Check Config Plz!");
        return ref configTbbattle_constants[0];
    }

}
}