//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbbattle_items
{
    public BlobArray<ConfigTbbattle_item> configTbbattle_items;

    public ref ConfigTbbattle_item Get(int id)
    {
        for (int i = 0; i < configTbbattle_items.Length; i++)
        {
            if (configTbbattle_items[i].id == id)
            {
                return ref configTbbattle_items[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbbattle_item,Check Config Plz!");
        return ref configTbbattle_items[0];
    }

}
}