//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbchapters
{
    public BlobArray<ConfigTbchapter> configTbchapters;

    public ref ConfigTbchapter Get(int id)
    {
        for (int i = 0; i < configTbchapters.Length; i++)
        {
            if (configTbchapters[i].id == id)
            {
                return ref configTbchapters[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbchapter,Check Config Plz!");
        return ref configTbchapters[0];
    }

}
}