//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbdraw_boxs
{
    public BlobArray<ConfigTbdraw_box> configTbdraw_boxs;

    public ref ConfigTbdraw_box Get(int id)
    {
        for (int i = 0; i < configTbdraw_boxs.Length; i++)
        {
            if (configTbdraw_boxs[i].id == id)
            {
                return ref configTbdraw_boxs[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbdraw_box,Check Config Plz!");
        return ref configTbdraw_boxs[0];
    }

}
}