//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbenergy_shops
{
    public BlobArray<ConfigTbenergy_shop> configTbenergy_shops;

    public ref ConfigTbenergy_shop Get(int id)
    {
        for (int i = 0; i < configTbenergy_shops.Length; i++)
        {
            if (configTbenergy_shops[i].id == id)
            {
                return ref configTbenergy_shops[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbenergy_shop,Check Config Plz!");
        return ref configTbenergy_shops[0];
    }

}
}