//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbequip_qualitys
{
    public BlobArray<ConfigTbequip_quality> configTbequip_qualitys;

    public ref ConfigTbequip_quality Get(int id)
    {
        for (int i = 0; i < configTbequip_qualitys.Length; i++)
        {
            if (configTbequip_qualitys[i].id == id)
            {
                return ref configTbequip_qualitys[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbequip_quality,Check Config Plz!");
        return ref configTbequip_qualitys[0];
    }

}
}