//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbequip_levels
{
    public BlobArray<ConfigTbequip_level> configTbequip_levels;

    public ref ConfigTbequip_level Get(int id)
    {
        for (int i = 0; i < configTbequip_levels.Length; i++)
        {
            if (configTbequip_levels[i].id == id)
            {
                return ref configTbequip_levels[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbequip_level,Check Config Plz!");
        return ref configTbequip_levels[0];
    }

}
}