//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTberrorcodes
{
    public BlobArray<ConfigTberrorcode> configTberrorcodes;

    public ref ConfigTberrorcode Get(int id)
    {
        for (int i = 0; i < configTberrorcodes.Length; i++)
        {
            if (configTberrorcodes[i].id == id)
            {
                return ref configTberrorcodes[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tberrorcode,Check Config Plz!");
        return ref configTberrorcodes[0];
    }

}
}