//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbevent_0s
{
    public BlobArray<ConfigTbevent_0> configTbevent_0s;

    public ref ConfigTbevent_0 Get(int id)
    {
        for (int i = 0; i < configTbevent_0s.Length; i++)
        {
            if (configTbevent_0s[i].id == id)
            {
                return ref configTbevent_0s[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbevent_0,Check Config Plz!");
        return ref configTbevent_0s[0];
    }

}
}