//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbfunds
{
    public BlobArray<ConfigTbfund> configTbfunds;

    public ref ConfigTbfund Get(int id)
    {
        for (int i = 0; i < configTbfunds.Length; i++)
        {
            if (configTbfunds[i].id == id)
            {
                return ref configTbfunds[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbfund,Check Config Plz!");
        return ref configTbfunds[0];
    }

}
}