//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbgifts
{
    public BlobArray<ConfigTbgift> configTbgifts;

    public ref ConfigTbgift Get(int id)
    {
        for (int i = 0; i < configTbgifts.Length; i++)
        {
            if (configTbgifts[i].id == id)
            {
                return ref configTbgifts[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbgift,Check Config Plz!");
        return ref configTbgifts[0];
    }

}
}