//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbgoodss
{
    public BlobArray<ConfigTbgoods> configTbgoodss;

    public ref ConfigTbgoods Get(int id)
    {
        for (int i = 0; i < configTbgoodss.Length; i++)
        {
            if (configTbgoodss[i].id == id)
            {
                return ref configTbgoodss[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbgoods,Check Config Plz!");
        return ref configTbgoodss[0];
    }

}
}