//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbguides
{
    public BlobArray<ConfigTbguide> configTbguides;

    public ref ConfigTbguide Get(int id)
    {
        for (int i = 0; i < configTbguides.Length; i++)
        {
            if (configTbguides[i].id == id)
            {
                return ref configTbguides[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbguide,Check Config Plz!");
        return ref configTbguides[0];
    }

}
}