//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbmails
{
    public BlobArray<ConfigTbmail> configTbmails;

    public ref ConfigTbmail Get(int id)
    {
        for (int i = 0; i < configTbmails.Length; i++)
        {
            if (configTbmails[i].id == id)
            {
                return ref configTbmails[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbmail,Check Config Plz!");
        return ref configTbmails[0];
    }

}
}