//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbmonster_types
{
    public BlobArray<ConfigTbmonster_type> configTbmonster_types;

    public ref ConfigTbmonster_type Get(int id)
    {
        for (int i = 0; i < configTbmonster_types.Length; i++)
        {
            if (configTbmonster_types[i].id == id)
            {
                return ref configTbmonster_types[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbmonster_type,Check Config Plz!");
        return ref configTbmonster_types[0];
    }

}
}