//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbmonster_attrs
{
    public BlobArray<ConfigTbmonster_attr> configTbmonster_attrs;

    public ref ConfigTbmonster_attr Get(int id)
    {
        for (int i = 0; i < configTbmonster_attrs.Length; i++)
        {
            if (configTbmonster_attrs[i].id == id)
            {
                return ref configTbmonster_attrs[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbmonster_attr,Check Config Plz!");
        return ref configTbmonster_attrs[0];
    }

}
}