//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbmonster_forations
{
    public BlobArray<ConfigTbmonster_foration> configTbmonster_forations;

    public ref ConfigTbmonster_foration Get(int id)
    {
        for (int i = 0; i < configTbmonster_forations.Length; i++)
        {
            if (configTbmonster_forations[i].id == id)
            {
                return ref configTbmonster_forations[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbmonster_foration,Check Config Plz!");
        return ref configTbmonster_forations[0];
    }

}
}