//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbmonopoly_event_lottos
{
    public BlobArray<ConfigTbmonopoly_event_lotto> configTbmonopoly_event_lottos;

    public ref ConfigTbmonopoly_event_lotto Get(int id)
    {
        for (int i = 0; i < configTbmonopoly_event_lottos.Length; i++)
        {
            if (configTbmonopoly_event_lottos[i].id == id)
            {
                return ref configTbmonopoly_event_lottos[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbmonopoly_event_lotto,Check Config Plz!");
        return ref configTbmonopoly_event_lottos[0];
    }

}
}