//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbmonopoly_events
{
    public BlobArray<ConfigTbmonopoly_event> configTbmonopoly_events;

    public ref ConfigTbmonopoly_event Get(int id)
    {
        for (int i = 0; i < configTbmonopoly_events.Length; i++)
        {
            if (configTbmonopoly_events[i].id == id)
            {
                return ref configTbmonopoly_events[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbmonopoly_event,Check Config Plz!");
        return ref configTbmonopoly_events[0];
    }

}
}