//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbpiggy_banks
{
    public BlobArray<ConfigTbpiggy_bank> configTbpiggy_banks;

    public ref ConfigTbpiggy_bank Get(int id)
    {
        for (int i = 0; i < configTbpiggy_banks.Length; i++)
        {
            if (configTbpiggy_banks[i].id == id)
            {
                return ref configTbpiggy_banks[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbpiggy_bank,Check Config Plz!");
        return ref configTbpiggy_banks[0];
    }

}
}