//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbqualitys
{
    public BlobArray<ConfigTbquality> configTbqualitys;

    public ref ConfigTbquality Get(int id)
    {
        for (int i = 0; i < configTbqualitys.Length; i++)
        {
            if (configTbqualitys[i].id == id)
            {
                return ref configTbqualitys[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbquality,Check Config Plz!");
        return ref configTbqualitys[0];
    }

}
}