//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbscenes
{
    public BlobArray<ConfigTbscene> configTbscenes;

    public ref ConfigTbscene Get(int id)
    {
        for (int i = 0; i < configTbscenes.Length; i++)
        {
            if (configTbscenes[i].id == id)
            {
                return ref configTbscenes[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbscene,Check Config Plz!");
        return ref configTbscenes[0];
    }

}
}