//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbsettings
{
    public BlobArray<ConfigTbsetting> configTbsettings;

    public ref ConfigTbsetting Get(int id)
    {
        for (int i = 0; i < configTbsettings.Length; i++)
        {
            if (configTbsettings[i].id == id)
            {
                return ref configTbsettings[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbsetting,Check Config Plz!");
        return ref configTbsettings[0];
    }

}
}