//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbshop_dailys
{
    public BlobArray<ConfigTbshop_daily> configTbshop_dailys;

    public ref ConfigTbshop_daily Get(int id)
    {
        for (int i = 0; i < configTbshop_dailys.Length; i++)
        {
            if (configTbshop_dailys[i].sign == id)
            {
                return ref configTbshop_dailys[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->sign:{id} in Tbshop_daily,Check Config Plz!");
        return ref configTbshop_dailys[0];
    }

}
}