//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbsign_accs
{
    public BlobArray<ConfigTbsign_acc> configTbsign_accs;

    public ref ConfigTbsign_acc Get(int id)
    {
        for (int i = 0; i < configTbsign_accs.Length; i++)
        {
            if (configTbsign_accs[i].id == id)
            {
                return ref configTbsign_accs[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbsign_acc,Check Config Plz!");
        return ref configTbsign_accs[0];
    }

}
}