//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbsign_dailys
{
    public BlobArray<ConfigTbsign_daily> configTbsign_dailys;

    public ref ConfigTbsign_daily Get(int id)
    {
        for (int i = 0; i < configTbsign_dailys.Length; i++)
        {
            if (configTbsign_dailys[i].id == id)
            {
                return ref configTbsign_dailys[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbsign_daily,Check Config Plz!");
        return ref configTbsign_dailys[0];
    }

}
}