//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbskill_effectNews
{
    public BlobArray<ConfigTbskill_effectNew> configTbskill_effectNews;

    public ref ConfigTbskill_effectNew Get(int id)
    {
        for (int i = 0; i < configTbskill_effectNews.Length; i++)
        {
            if (configTbskill_effectNews[i].id == id)
            {
                return ref configTbskill_effectNews[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbskill_effectNew,Check Config Plz!");
        return ref configTbskill_effectNews[0];
    }

}
}