//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbskill_bindings
{
    public BlobArray<ConfigTbskill_binding> configTbskill_bindings;

    public ref ConfigTbskill_binding Get(int id)
    {
        for (int i = 0; i < configTbskill_bindings.Length; i++)
        {
            if (configTbskill_bindings[i].id == id)
            {
                return ref configTbskill_bindings[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbskill_binding,Check Config Plz!");
        return ref configTbskill_bindings[0];
    }

}
}