//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbskill_qualitys
{
    public BlobArray<ConfigTbskill_quality> configTbskill_qualitys;

    public ref ConfigTbskill_quality Get(int id)
    {
        for (int i = 0; i < configTbskill_qualitys.Length; i++)
        {
            if (configTbskill_qualitys[i].id == id)
            {
                return ref configTbskill_qualitys[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbskill_quality,Check Config Plz!");
        return ref configTbskill_qualitys[0];
    }

}
}