//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbspecial_effect_movements
{
    public BlobArray<ConfigTbspecial_effect_movement> configTbspecial_effect_movements;

    public ref ConfigTbspecial_effect_movement Get(int id)
    {
        for (int i = 0; i < configTbspecial_effect_movements.Length; i++)
        {
            if (configTbspecial_effect_movements[i].id == id)
            {
                return ref configTbspecial_effect_movements[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbspecial_effect_movement,Check Config Plz!");
        return ref configTbspecial_effect_movements[0];
    }

}
}