//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbsweep_timess
{
    public BlobArray<ConfigTbsweep_times> configTbsweep_timess;

    public ref ConfigTbsweep_times Get(int id)
    {
        for (int i = 0; i < configTbsweep_timess.Length; i++)
        {
            if (configTbsweep_timess[i].id == id)
            {
                return ref configTbsweep_timess[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbsweep_times,Check Config Plz!");
        return ref configTbsweep_timess[0];
    }

}
}