//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbtasks
{
    public BlobArray<ConfigTbtask> configTbtasks;

    public ref ConfigTbtask Get(int id)
    {
        for (int i = 0; i < configTbtasks.Length; i++)
        {
            if (configTbtasks[i].id == id)
            {
                return ref configTbtasks[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbtask,Check Config Plz!");
        return ref configTbtasks[0];
    }

}
}