//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbtag_funcs
{
    public BlobArray<ConfigTbtag_func> configTbtag_funcs;

    public ref ConfigTbtag_func Get(int id)
    {
        for (int i = 0; i < configTbtag_funcs.Length; i++)
        {
            if (configTbtag_funcs[i].id == id)
            {
                return ref configTbtag_funcs[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbtag_func,Check Config Plz!");
        return ref configTbtag_funcs[0];
    }

}
}