//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbtalent_levels
{
    public BlobArray<ConfigTbtalent_level> configTbtalent_levels;

    public ref ConfigTbtalent_level Get(int id)
    {
        for (int i = 0; i < configTbtalent_levels.Length; i++)
        {
            if (configTbtalent_levels[i].id == id)
            {
                return ref configTbtalent_levels[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbtalent_level,Check Config Plz!");
        return ref configTbtalent_levels[0];
    }

}
}