//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;



namespace cfg.blobstruct{
public struct ConfigTbuser_levels
{
    public BlobArray<ConfigTbuser_level> configTbuser_levels;

    public ref ConfigTbuser_level Get(int id)
    {
        for (int i = 0; i < configTbuser_levels.Length; i++)
        {
            if (configTbuser_levels[i].id == id)
            {
                return ref configTbuser_levels[i];
            }
        }
        Debug.LogError($"Error! Can't find config with key->id:{id} in Tbuser_level,Check Config Plz!");
        return ref configTbuser_levels[0];
    }

}
}