//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbuser_avatar
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbuser_avatar> configTbuser_avatars,Tables tables)
    { 
        configTbuser_avatars[i].id = tables.Tbuser_avatar.DataList[i].id;
        configTbuser_avatars[i].type = tables.Tbuser_avatar.DataList[i].type;
        configTbuser_avatars[i].quality = tables.Tbuser_avatar.DataList[i].quality;
        configTbuser_avatars[i].sort = tables.Tbuser_avatar.DataList[i].sort;
        configTbuser_avatars[i].name = tables.Tbuser_avatar.DataList[i].name;
        configTbuser_avatars[i].desc = tables.Tbuser_avatar.DataList[i].desc;
        configTbuser_avatars[i].icon = tables.Tbuser_avatar.DataList[i].icon;
        configTbuser_avatars[i].preview = tables.Tbuser_avatar.DataList[i].preview;
    }


    /// <summary>
    /// id
    /// </summary>
    public int id;
    /// <summary>
    /// 类型
    /// </summary>
    public int type;
    /// <summary>
    /// 品质
    /// </summary>
    public int quality;
    /// <summary>
    /// 排序
    /// </summary>
    public int sort;
    /// <summary>
    /// 名称
    /// </summary>
    public FixedString128Bytes name;
    /// <summary>
    /// 描述
    /// </summary>
    public FixedString128Bytes desc;
    /// <summary>
    /// 图片资源(图片资源)
    /// </summary>
    public FixedString128Bytes icon;
    /// <summary>
    /// 预览图(图片资源)
    /// </summary>
    public FixedString128Bytes preview;
}
}