//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;



namespace cfg.blobstruct{

public  struct ConfigTbweapon
{
    public static void Create(int i,ref BlobBuilder builder,ref BlobBuilderArray<ConfigTbweapon> configTbweapons,Tables tables)
    { 
        configTbweapons[i].id = tables.Tbweapon.DataList[i].id;
        configTbweapons[i].type = tables.Tbweapon.DataList[i].type;
        configTbweapons[i].name = tables.Tbweapon.DataList[i].name;
        configTbweapons[i].pic = tables.Tbweapon.DataList[i].pic;
        configTbweapons[i].desc = tables.Tbweapon.DataList[i].desc;
        configTbweapons[i].quality = tables.Tbweapon.DataList[i].quality;
        configTbweapons[i].diamond = tables.Tbweapon.DataList[i].diamond;
        configTbweapons[i].model = tables.Tbweapon.DataList[i].model;
        configTbweapons[i].atkType = tables.Tbweapon.DataList[i].atkType;
        configTbweapons[i].displayType = tables.Tbweapon.DataList[i].displayType;
        configTbweapons[i].paraAtk = tables.Tbweapon.DataList[i].paraAtk;
        configTbweapons[i].paraInterval = tables.Tbweapon.DataList[i].paraInterval;
        configTbweapons[i].paraForce = tables.Tbweapon.DataList[i].paraForce;
        configTbweapons[i].paraSpeed = tables.Tbweapon.DataList[i].paraSpeed;
        var allocatemoveTypes =
        builder.Allocate(ref configTbweapons[i].moveType,
        tables.Tbweapon.DataList[i].moveType.Count);
        for (var moveTypes = 0; moveTypes < tables.Tbweapon.DataList[i].moveType.Count; moveTypes++)
        {
            allocatemoveTypes[moveTypes] = tables.Tbweapon.DataList[i].moveType[moveTypes];
        }
        configTbweapons[i].para1 = tables.Tbweapon.DataList[i].para1;
        configTbweapons[i].para2 = tables.Tbweapon.DataList[i].para2;
        configTbweapons[i].para3 = tables.Tbweapon.DataList[i].para3;
        configTbweapons[i].displayTime = tables.Tbweapon.DataList[i].displayTime;
        var allocatedisplayPara1s =
        builder.Allocate(ref configTbweapons[i].displayPara1,
        tables.Tbweapon.DataList[i].displayPara1.Count);
        for (var displayPara1s = 0; displayPara1s < tables.Tbweapon.DataList[i].displayPara1.Count; displayPara1s++)
        {
            allocatedisplayPara1s[displayPara1s] = tables.Tbweapon.DataList[i].displayPara1[displayPara1s];
        }
        var allocatedisplayPara2s =
        builder.Allocate(ref configTbweapons[i].displayPara2,
        tables.Tbweapon.DataList[i].displayPara2.Count);
        for (var displayPara2s = 0; displayPara2s < tables.Tbweapon.DataList[i].displayPara2.Count; displayPara2s++)
        {
            allocatedisplayPara2s[displayPara2s] = tables.Tbweapon.DataList[i].displayPara2[displayPara2s];
        }
    }


    /// <summary>
    /// id
    /// </summary>
    public int id;
    /// <summary>
    /// 类型
    /// </summary>
    public int type;
    /// <summary>
    /// 名称
    /// </summary>
    public FixedString128Bytes name;
    /// <summary>
    /// 图片(图片资源)
    /// </summary>
    public FixedString128Bytes pic;
    /// <summary>
    /// 描述
    /// </summary>
    public FixedString128Bytes desc;
    /// <summary>
    /// 品质
    /// </summary>
    public int quality;
    /// <summary>
    /// 图鉴-解锁领取比特币
    /// </summary>
    public int diamond;
    /// <summary>
    /// 模型
    /// </summary>
    public FixedString128Bytes model;
    /// <summary>
    /// 攻击类型
    /// </summary>
    public int atkType;
    /// <summary>
    /// 动画类型
    /// </summary>
    public int displayType;
    /// <summary>
    /// 攻击力系数
    /// </summary>
    public int paraAtk;
    /// <summary>
    /// 攻击间隔
    /// </summary>
    public int paraInterval;
    /// <summary>
    /// 推力系数
    /// </summary>
    public int paraForce;
    /// <summary>
    /// 移动速度系数
    /// </summary>
    public int paraSpeed;
    /// <summary>
    /// 移动规则
    /// </summary>
    public BlobArray<int> moveType;    
    /// <summary>
    /// 参数1
    /// </summary>
    public int para1;
    /// <summary>
    /// 参数2
    /// </summary>
    public int para2;
    /// <summary>
    /// 参数3
    /// </summary>
    public int para3;
    /// <summary>
    /// 总时间(毫秒)
    /// </summary>
    public int displayTime;
    /// <summary>
    /// 武器攻击动画参数
    /// </summary>
    public BlobArray<int> displayPara1;    
    /// <summary>
    /// 普通Boss施法动画参数/角色死亡武器动画参数
    /// </summary>
    public BlobArray<int> displayPara2;    
}
}